packages/start/components/Outlet.tsx
* Not optimal but makes nested routes possible
=> fix(routes): create a working route substructure #15

lerna.json, packages/start/package.json
Quick untested PR bumping to current solid-js versions. Not sure if these are compatible but at a glance they seem fine.
=> Updated solid-start dependencies

packages/start/components/index.tsx
Closes https://github.com/solidjs/solid-start/issues/54
=> exporting StartContext & StartProvider from solid-start/components

packages/start/bin.cjs
=> fix: solid-start dev --port $PORT

packages/start/runtime/devServer.js, packages/start/server/babel.js
It's only for dev, I did not test it in build mode.
Please, do not forget use node path methods when working with paths
=> fix windows paths in dev mode

packages/start/runtime/fetch.js
Closes https://github.com/solidjs/solid-start/issues/68
=> POST,PUT,PATCH: Request body

.github/workflows/test.yml, docs/src/root.tsx, docs/src/routes/api/forms/createAction.md, docs/src/routes/api/forms/createform.md, examples/with-auth/src/routes/index.tsx, examples/with-auth/src/routes/login.tsx, examples/with-prisma/src/routes/index.tsx, examples/with-prisma/src/routes/login.tsx, fixtures/cloudflare-workers/src/routes/index.tsx, fixtures/cloudflare-workers/src/routes/login.tsx, packages/start/server/babel.js, packages/start/server/index.ts, packages/start/server/responses.ts
Use `server.request` to get access to the server request. it is compiled to a version of `this.request`. You are allowed to use arrow functions safely now, we compile them to function declarations. This only works for a function thats inlined with the server call.
=> Server-context

packages/start-deno/README.md, packages/start-deno/entry.js, packages/start-deno/index.js, packages/start-deno/package.json, pnpm-lock.yaml
Adapter for deno-deploy platform
=> Deno-deploy

packages/start-netlify/package.json, packages/start-node/package.json, packages/start-static/package.json, packages/start-vercel/package.json
=> fix adapters peerDependencies

packages/start/api/index.ts, packages/start/api/middleware.ts, packages/start/plugin.js, packages/start/routes.js, packages/start/server/serverFunction.ts
I needed this for my project so I quickly wrote this. It supports parameters and wildcards. Implemented using a simple tree and recursion.
I'm passing the parameters as a second argument to the handler, could be passed in the context instead.
The naming of certain things also need a review (getApiHandler returning an object with a handler is a bit awkward).
Feel free to modify this or to use something else.
=> [WIP] Add api router that supports route params

packages/start/data/createRouteAction.tsx, test/action-test.ts
=> `createRouteAction` should remove submission from `pending` on error

packages/start/data/createRouteAction.tsx, test/redirect-test.ts
=> Fix: make external URL redirectable inside actions/server functions.

packages/start-node/server.js, test/event-stream-test.ts
=> fix: compression on event stream

packages/start/plugin.js, packages/start/root/FileRoutes.tsx, packages/start/root/Links.tsx, packages/start/routes.js, test/css-link-test.ts, test/link-test.ts
Idea taken from: https://remix.run/docs/en/v1/guides/routing#pathless-layout-routes
Implemented the same as described on the remix page.
Removed support for index nested routes.
=> Pathless Layout Routes

examples/bare/src/routes/[...404].tsx
There were some unused imports in the 404 page, I removed them.
=> Remove unused imports on 404 page.

package.json, packages/create-solid/package.json, packages/start-cloudflare-pages/index.js, packages/start-cloudflare-pages/package.json, packages/start-cloudflare-workers/index.js, packages/start-cloudflare-workers/package.json, packages/start-deno/index.js, packages/start-deno/package.json, packages/start-netlify/index.js, packages/start-netlify/package.json, packages/start-node/index.js, packages/start-node/package.json, packages/start-static/index.js, packages/start-static/package.json, packages/start-vercel/index.js, packages/start-vercel/package.json, packages/start/package.json, pnpm-lock.yaml
Was not able to run the tests due to installing the current version of solid-start from npm. Feel free to ignore this PR if more work is needed to perform the upgrade.
=> vite v3 upgrade: fixes https://github.com/solidjs/solid-start/issues/185

CONTRIBUTING.md
Hi there! 👋👋
I tried to run the example project mentioned in CONTRIBUTING.md but the project name was wrong.
=> Fix example script in contribution guide

examples/bare/src/components/Counter.tsx, examples/with-mdx/src/components/Counter.tsx, examples/with-solid-styled/src/components/Counter.tsx, examples/with-tailwindcss/src/components/Counter.tsx, examples/with-vitest/src/components/Counter.tsx
I think this is supposed to be a function call?
=> Fix reactivity usage in templates

packages/start/error-boundary/ErrorBoundary.tsx
Per discord conversation about forwarding it
=> Forward reset function to re-exported ErrorBoundary

packages/start/data/createRouteAction.tsx
Fix for #310 
Exact solution we discussed on Discord, did some manual testing around retrying etc., seems to work correctly 😃
=> Track requests per submition in multi action

examples/bare/README.md, examples/durable-objects-websocket/README.md, examples/hackernews/README.md, examples/todomvc/README.md, examples/with-auth/README.md, examples/with-mdx/README.md, examples/with-solid-styled/README.md, examples/with-tailwindcss/README.md, examples/with-vitest/README.md, test/template/README.md
Minor update in the README in the examples
=> Update solid-start docs link in the README in the examples

docs/api/useServerEvent.md
=> Small typo

packages/start/server/server-functions/browser.ts
=> Adding a truthy check to value in browser.ts

examples/movies/src/assets/css/components/_card.scss, examples/movies/src/components/Card.tsx, examples/movies/src/components/Poster.module.scss, examples/movies/src/components/Poster.tsx, examples/movies/src/routes/movie/[movieId]/(overview)/MovieInfo.tsx
- Created Poster component to add 3d effect to Posters
- Removed a styling in the card class that was conflicting with the poster (i've added the scaling in the Poster css)
=> Created Poster component to add 3d effect to Posters

docs/core-concepts/routing.md, docs/getting-started/what-is-solidstart.md
Added a little more detail and some helpful links to the docs.
=> Added some minor detail to docs

docs/core-concepts/static-assets.md
=> Grammar fix

examples/with-prisma/src/routes/login.tsx
fix an error in the `getUser` call by passing correct arguments
=> fix: `getUser`

packages/start/dev/server.js
typeof err === 'string' check to avoid IDE type error
=> process: unhandledRejection: err.stack

examples/with-vitest/README.md, examples/with-vitest/package.json, examples/with-vitest/src/components/Counter.test.tsx, examples/with-vitest/tsconfig.json, examples/with-vitest/vite.config.ts, pnpm-lock.yaml
Updated the example and fixed the configuration so that the tests will run again.
=> fix vitest example

packages/start/dev/server.js
fixes https://github.com/solidjs/solid-start/issues/469
=> start: dev/server: unhandled instead of unhandler

packages/start/data/Form.tsx, packages/start/data/createRouteAction.tsx, packages/start/data/createRouteData.tsx, packages/start/dev/create-index-html.js, packages/start/entry-client/mount.tsx, packages/start/entry-server/StartServer.tsx, packages/start/entry-server/render.ts, packages/start/error-boundary/ErrorBoundary.tsx, packages/start/islands/index.tsx, packages/start/package.json, packages/start/root/InlineStyles.tsx, packages/start/root/Links.tsx, packages/start/root/Scripts.tsx, packages/start/root/index.tsx, packages/start/router.tsx, packages/start/server/components/HttpHeader.tsx, packages/start/server/components/HttpStatusCode.tsx, packages/start/server/middleware.ts, packages/start/server/responses.ts, packages/start/server/server-functions/browser.ts, packages/start/server/server-functions/server.ts, packages/start/virtual/entry-server.tsx, packages/start/vite/plugin.d.ts, packages/start/websocket/index.ts
I tried to fix the types of the .ts files. Next step would be to move .js files to .ts one after another.
=> start: fix types

docs/api/entry-server.md
I just noticed this small incorrectness while reading through the docs. But anyways, awesome project 🔥
=> Fix wrong description of the entry-server.tsx docs

packages/start/entry-server/render.ts, packages/start/root/InlineStyles.tsx, packages/start/virtual/entry-server.tsx
Sorry for introducing an error in the fixed types. Here's the fix.
=> fix for fixed types

docs/getting-started/what-is-solidstart.md
Fixed grammar, changed it's to its.
=> chore: fix grammar

docs/api/createSessionStorage.md
I was reading the docs and noticed createData and updateData params changed a bit.
=> Docs: Update createData and updateData functions on createSessionStorage example

packages/start/vite/index.d.ts, packages/start/vite/plugin.d.ts
This PR is to fix https://github.com/solidjs/solid-start/issues/552
=> Fix typescript error with adapter

docs/api/createCookieSessionStorage.md
Related - https://github.com/solidjs/solid-start/issues/556, https://github.com/OrJDev/create-jd-app/issues/24
=> doc: SESSION_SECRET should be private

docs.root.tsx
=> Fix sidebar nav bottom padding scroll issue

docs/advanced/session.md
i already made this pr before, it was merged but someone reverted it for some reason?
https://github.com/solidjs/solid-start/pull/578
edit: looks like its a different file, my bad - missed it last time.
=> docs: SESSION_SECRET should be private

docs/advanced/middleware.mdx
=> middleware docs

packages/start-cloudflare-pages/index.d.ts, packages/start-cloudflare-workers/index.d.ts
Took me some chin scratching to figure out Miniflare, `solid-start dev`, and `.env` files, so I documented it.
=> Better MiniflareOptions docs

packages/start-aws/entry.mjs, packages/start-netlify/entry.js, packages/start-node/server.js, packages/start-vercel/entry-prerender.js, packages/start-vercel/entry.js, packages/start/dev/server.js, packages/start/node/fetch.js, packages/start/package.json, pnpm-lock.yaml
This should fix #293 by adding cookie splitting.  Keep in mind you need to use the `append` rather than the `set` method to set multiple `set-cookie` headers.
=> fix #293 multi set-cookie

packages/start-aws/entry.mjs, packages/start-netlify/entry.js, packages/start-vercel/entry-prerender.js, packages/start-vercel/entry.js
fixes https://github.com/solidjs/solid-start/issues/658
=> import from solid-start/node/fetch.js

examples/todomvc/package.json, examples/with-auth/package.json, package.json, packages/start-aws/package.json, packages/start-cloudflare-pages/package.json, packages/start-cloudflare-workers/package.json, packages/start-deno/package.json, packages/start-netlify/package.json, packages/start-node/package.json, packages/start-static/package.json, packages/start-vercel/package.json, packages/start/package.json, pnpm-lock.yaml
=> Bump rollup from 2.x to 3.10

packages/start/vite/plugin.js, test/misc-test.ts
=> fix missing return statement

docs/core-concepts/routing.md
`[[id]].tsx` for optional parameter in file based routing.
=> docs: file based routing optional parameter

scripts/bump.cjs
Helps prevent issues like https://github.com/solidjs/solid-start/issues/690
Could also do others like `@solidjs/meta` or `@solidjs/router` - just say the word!
=> `bump.cjs` updates example deps

packages/start/vite/plugin.js
Made a PR so I can use the CI to test this stuff.
=> try to fix windows with ssr:false

packages/start/package.json
Closes https://github.com/solidjs/solid-start/issues/715
=> fix: set adapters as peer dependencies

pnpm-lock.yaml
1. Checked out main
2. Run `pnpm i`
=> Update lockfile after solidjs 1.6.10 update

examples/bare/package.json, examples/hackernews/package.json, examples/todomvc/package.json, examples/with-auth/package.json, examples/with-authjs/package.json, examples/with-mdx/package.json, examples/with-prisma/package.json, examples/with-solid-styled/package.json, examples/with-tailwindcss/package.json, examples/with-vitest/package.json, examples/with-websocket/package.json, package.json, packages/start-aws/package.json, packages/start-cloudflare-pages/package.json, packages/start-cloudflare-workers/package.json, packages/start-deno/package.json, packages/start-netlify/package.json, packages/start-node/package.json, packages/start-static/package.json, packages/start-vercel/package.json, packages/start/bin.cjs, packages/start/package.json, pnpm-lock.yaml, test/package.json, test/template/package.json
Fixes #674 , Fixes #660 
@ryansolid , I believe this does the trick. It also fixes the lockfile after 0.2.22 release
=> Vite 4.1.4

packages/start-netlify/index.js
Add JSDoc comment for netlify vite adapter #829
Thanks for the awesome work on this!
=> Add JSDoc comment for netlify vite adapter

examples/with-tailwindcss/astro.config.js, examples/with-tailwindcss/package.json
it just missed the astro tailwindcss plugin, so added it
=> fix: with tailwindcss example

packages/start/astro/index.d.ts, packages/start/vite/plugin.d.ts
it makes the world a better place
=> Add options param types to astro integration

docs/getting-started/project-setup.mdx, examples/with-trpc/src/utils/api.ts, packages/start-cloudflare-workers/index.js, packages/start-deno/index.js, packages/start-node/index.js, packages/start-static/index.js, packages/start/bin.cjs, packages/start/package.json, packages/start/server/server-functions/server.ts, test/unit/server-functions.spec.tsx
https://github.com/solidjs/solid-start/issues/905
=> Fix econnrefused node18

docs/api/createRouteAction.md
The `createRouteAction` page on the docs mentions in passing the Form API feature, but doesn't go into detail or provide an example on how to use it.
Updates the page to match a similar execution as the `createServerAction$` API page that gives a working real world example when users need client-side forms.
=> docs(api): update createRouteAction.md

docs/core-concepts/state-management.mdx
State Management page is empty.
Updates page with all the details described in the original list.
=> docs: update state-management.mdx

docs/api/createRouteAction.md
=> Update createRouteAction.md typo

CONTRIBUTING.md, package.json, test/package.json
Not all testing related run scripts are defined in the root package.json
Added the following run scripts to root package.json
- install:playwright
- show:test-report
Updated CONTRIBUTING.md
=> Add testing related run scripts to root package.json

packages/start/server/server-functions/server.ts
_**I don't really understand how to write a test for this case.**_
This fixes #985
When calling a server function from an API route, when create the request context manually.
=> Fix missing request context for getApiHandler and API routes Closes #985

package.json, pnpm-lock.yaml
Missed the docs on #1021. Sorry about that.
Docs working again. Fixes #1022
=> update solid-js version of docs to ^1.7.11

examples/with-websocket/src/entry-server.tsx, examples/with-websocket/vite.config.ts, packages/start-cloudflare-workers/index.js
example `with-websocket` doesn't work correctly.
example `with-websocket` work correctly.
=> fix: websocket example bug

packages/start-node/server.js, packages/start/api/middleware.ts, packages/start/dev/server.js, packages/start/server/types.tsx
No reference to the server for possible socket.io implementation.
Added reference to the the server and the type.
#1017
=> [Feature]: Add Server Reference to FetchEvent Type for WebSocket Communication with Socket.IO

docs/api/createRouteAction.md
Clicked link takes a long time to load and then shows a white page.
Loads the intended page.
=> Fix broken link

packages/start-aws/index.d.ts, packages/start-deno/index.d.ts, packages/start-netlify/index.d.ts, packages/start-node/index.d.ts
asw,deno,netlify,node no type defined
Add asw,deno,netlify,node type define file.
=> Add asw,deno,netlify,node type define

pnpm-lock.yaml, test/package.json
Tests fail on Node 20.x
Tests pass on Node 20.x
Updated `@playwright/test` to `1.38.1`. Fixes #1058
=> Get tests to run on node 20.x

packages/start/server/routeDataHmr.js
*@babel/generator* and *@babel/template" has not publish esm version.
It caused this [bug](https://github.com/solidjs/solid-start/discussions/1070#discussion-5671253)
[reference issue](https://github.com/babel/babel/issues/15269)
=> Solve discussion #1070

packages/start-new/config/index.js, packages/start-new/shared/lazyRoute.tsx
- Lazy route dynamic import not working
- Runtime path on client router not normalized (import fails)
- Use new import helper in lazy route
- Normalize runtime path on client router
=> [vinxi] More Windows fixes

packages/start/config/server-handler.js, packages/start/config/server-runtime.jsx, packages/start/package.json, pnpm-lock.yaml
- Server functions now use `seroval` for serializing/deserializing server function data between server and client.
- Server functions are also now capable of streaming data.
=> feat: new server functions

docs/routes/api/build.md, docs/routes/api/dev.md, docs/routes/api/start.md
Arguably, this part of the docs belong inside of Vinxi docs, but since they aren't complete this could work temporarily
Docs
=> Clarify in docs that CLI is vinxi

packages/start/config/index.d.ts
When you use vite.config.ts you don't get typings
Now when using typescript you get proper typings
=> Add config types

docs/app.tsx, docs/components/index.css
Misc visual changes.
It also fixes a bug, where an empty space was rendered in the sidebar when the link matched the subsection title
=> Misc visual improvements

docs/app.tsx, docs/components/A.tsx, docs/components/components.tsx, examples/bare/package.json, examples/basic/package.json, examples/experiments/package.json, examples/hackernews/package.json, examples/todomvc/package.json, examples/with-auth/package.json, examples/with-mdx/package.json, examples/with-prisma/package.json, examples/with-solid-styled/package.json, examples/with-tailwindcss/package.json, examples/with-trpc/package.json, package.json, packages/start/config/index.d.ts, packages/start/package.json, packages/start/server/StartServer.tsx, packages/start/server/page-event.tsx, pnpm-lock.yaml, vite.config.ts
=> fixed islands build in prod, vinxi 0.0.54

packages/start/server/StartServer.tsx
See #1186 
I added the global `$R` variable here too, as in `server/spa/StartServer.tsx`.
I'm not sure if this is correct way, but it fixes the error for my repro.
=> Add missing global `$R`

docs/routes/api/server.md
=> "server$" -> "use server"

packages/start/config/server-runtime.jsx
deserializeStream may fail due to truncated large values that do not fit in a single ReadableStream chunk
The stream is exhausted first prior to attempting deserialization
Fixes #1243
=> Support large values in deserializeStream

packages/start/shared/lazyRoute.tsx
=> feat: preload styles when lazy routes are preloaded

packages/start/config/server-handler.js, packages/start/config/server-runtime.jsx
- Fixes #1249 
- The current chunking algorithm now goes in the format `;<bytes in hexadecimal>;<data>`
- This specific format is selected to preserve the current MIME type for the server functions.
- Each streamed chunk has an additional 12 bytes for the byte info
- The multi-line comment variant involves around 13 bytes (4 + 8 + 1 for the suffix semicolon in data)
- The comma variant is as decent as the current format but probably the formatting in Chrome might affect it.
- A "chunk" can contain up to `2^32` bytes (up to 4.2 GB). In the future, we can adjust this to `2^64` (total of 20 bytes for a header) but I guess it's almost impossible to have more than 4.2GB worth of data, let alone 1GB of it.
Some previews:
=> feat: New server functions chunking algorithm

packages/start/shared/dev-overlay/CodeView.tsx, packages/start/shared/dev-overlay/styles.css
- Fix Oniguruma WASM loading method
- Fix color for error highlight
=> Fix dev overlay stuff

README.md
- [N/A] Tests for the changes have been added (for bug fixes / features)
=> Fix typos and capitalization in README

docs/app.tsx, docs/components/components.tsx, docs/components/index.css, docs/routes/api/HttpStatusCode.md, docs/routes/api/server.md, docs/routes/core-concepts/actions.md, docs/routes/core-concepts/data-loading.mdx, docs/routes/core-concepts/route-prerendering.mdx, docs/routes/core-concepts/state-management.mdx
=> Docs: Typography and code highlight fixes

examples/with-vitest/package.json, examples/with-vitest/setupVitest.ts, examples/with-vitest/src/components/Counter.test.tsx, examples/with-vitest/vitest.config.ts, pnpm-lock.yaml
vitest will work without much configuration (unfortunately, vinxi does not convey testing mode, so we still need a vitest.config.ts).
=> vitest example: reduced configuration

examples/bare/package.json, examples/basic/package.json, examples/experiments/package.json, examples/hackernews/package.json, examples/todomvc/package.json, examples/with-auth/package.json, examples/with-mdx/package.json, examples/with-prisma/package.json, examples/with-solid-styled/package.json, examples/with-tailwindcss/package.json, examples/with-trpc/package.json, examples/with-vitest/package.json, package.json, packages/start/config/index.js, packages/start/package.json, pnpm-lock.yaml
SSR and client code get different asset urls importing the same asset 
SSR and client code get the same asset urls importing the same asset
=> bump vinxi to 0.1.6 and add link between ssr router and client router

docs/routes/api/GET.md, docs/routes/api/RequestEventLocals.md, docs/routes/api/ReturnResponses.md, docs/routes/api/vite.md
=> Docs: 0.5 Updates

.changeset/nervous-seas-invite.md, packages/start/shared/dev-overlay/createStackFrame.ts
=> Fix dev overlay logs

.changeset/perfect-phones-invite.md, packages/start/server/islands/index.tsx, packages/start/shared/dev-overlay/DevOverlayDialog.tsx, packages/start/shared/dev-overlay/createStackFrame.ts
Continuation of #1312: type imports that weren't initially caught until using more features
=> fix: add missing type declaration to imports

.changeset/dirty-lizards-tap.md, packages/start/package.json, packages/start/src/shared/dev-overlay/index.tsx, pnpm-lock.yaml
=> fix: remove dev overlay in prod

docs/routes/api/RequestEvent.md
=> docs: fix typo

README.md, docs/app.tsx, docs/entry-server.tsx, docs/routes/getting-started/what-is-solidstart.md
=> beta -> RC

examples/notes/package.json, pnpm-lock.yaml
Make it more convenient to compare the example code with the utility library documentation.
I have tested manually because I could not find tests for the code in this example. It might be worthwhile to add some testing to the examples, although it could make the example projects more complex.
1. Run  `pnpm create solid` 
2. Select the `notes` template
The created project contains version of `marked`  eight major releases behind current and of `date-fns` a major version behind. When playing with the code, it was not clear whether I could rely on the latest documentation for these libraries, and whether I could update them without breaking.
`marked` and `date-fns` use the latest major …
=> chore(examples): update marked and date-fns

docs/routes/getting-started/what-is-solidstart.md
=> Add link to new docs

docs/routes/advanced/session.md
- [x ] Tests for the changes have been added (for bug fixes / features)
The session type is determined in the update call instead of in the session definition
The session type is defined in the session definition
=> Improved typing of session

docs/routes/advanced/session.md
When using the code sample, you get a typing error indicating that a parameter is missing
I've added the parameter
=> Updated docs where a parameter was missing to the `cache` call

.changeset/fluffy-impalas-listen.md, examples/with-trpc/package.json, examples/with-trpc/src/server/api/routers/example.ts, package.json, pnpm-lock.yaml
- [ n/a ] Tests for the changes have been added (for bug fixes / features)
-> manual check of the example is working as expected
usage of deprecated package `@decs/typeschema`
removal of package `@decs/typeschema`
replaced with trpc recommended replacement package `@typeschema/valibot`
cleanup of root project dependencies for `@trpc/client`, `@trpc/server` and `@decs/typeschema`
=> trpc example dependencies update

docs/components/icons/platform/aws-logo.tsx, docs/components/icons/platform/azure-logo.tsx, docs/components/icons/platform/cloudflare-logo.tsx
Some logos are too big compared with others. This kinda balances the sizes
cc: @atilafassina @LadyBluenotes @davedbase
=> refactor: logos size

docs/app.tsx, public/robots.txt
Adds meta information to the new landing page
=> feat: add meta info

docs/components/code-snippet.tsx
=> Add bun to PM tabs on landing

.gitattributes
This HTML file is very large
Ignoring HTML in programming language statistics
=> Ignoring HTML in programming language statistics

examples/with-trpc/src/routes/api/trpc/[trpc].ts
=> chore: update [trpc].ts

packages/start/package.json
Relate issue #1505, package.json add `env.d.ts` export(only type)
=> chore(type): `env.d.ts` add exports

docs/components/theme-toggle.tsx
When using light theme the themes selector item focused text color is difficult to see(dark text on dark background).
Changed the color to light text on dark background on light theme to provide more contrast when focused.
=> improved theme selector focused item contrast in light theme

.changeset/tender-dogs-tan.md, packages/start/src/shared/ErrorBoundary.tsx
The production builds swallow runtime errors, making it extremely hard to debug production specific bugs.
Errors that are catched by the ErrorBoundary are logged in the console.
One problem with this is, that people likely wanna use a different logger than `console.error` - depending on their infrastructure. Ideally we should have some way to globally configure the logger for internal systems such as the ErrorBoundary 🤔. That would also help to make the logger deploy-platform agnostic.
=> feat: log errors in production

examples/with-tailwindcss/src/app.css
closes #1563.
If the system theme changes to night mode, a newly created Solid app would stay in day mode.
A newly created Solid app will switch themes when the system theme changes.
=> feat: automatic theme switching for Tailwind

.github/workflows/cr.yml
We have continuous releases now! 
We need to have the app installed on this repo, so the CI of pkg.pr.new can run! 
Here you go: https://github.com/apps/pkg-pr-new
=> feat: continuous releases using pkg.pr.new

.changeset/sixty-news-fly.md, packages/start/src/shared/ErrorBoundary.tsx, packages/start/src/shared/dev-overlay/index.tsx
=> fix https://discord.com/channels/722131463138705510/910635844119982080/1280563749773639770

.changeset/lovely-grapes-share.md, packages/start/package.json
`vite-plugin-inspect` is included as a dependency and is not imported in the package. When people install start they are installing this package as well because of this.  
Removes the dependency.
=> removed unused dependency

packages/start/package.json, packages/start/src/shared/dev-overlay/CodeView.tsx, pnpm-lock.yaml
[shikiji](https://www.npmjs.com/package/shikiji?activeTab=readme) is deprecated because is now merge with [shiki](https://www.npmjs.com/package/shiki).
Shikiji was replaced by Shiki
=> Replace shikiji with shiki

examples/with-vitest/package.json, pnpm-lock.yaml
Trivial vitest bump in with-vitest example
=> Use Vitest 3 in with-vitest example

package.json, packages/start/package.json, pnpm-lock.yaml, pnpm-workspace.yaml, tests/server-function/package.json
**What kind of change does this PR introduce?**
infrastructure changes
**What is the new behavior?**
as we add more packages and consume the same ecosystem dependencies, we can lock the versions from the tests to the ones used in the actual package. 
--
@birkskyum
=> Workspace versions

.stackblitzrc, package.json, pnpm-lock.yaml
=> chore: remove unused dependencies

tests/server-function/cypress/e2e/server-function.cy.ts, tests/server-function/src/app.tsx, tests/server-function/src/functions/use-is-server.ts, tests/server-function/src/functions/use-node-builtin.ts, tests/server-function/src/functions/use-npm-module.ts, tests/server-function/src/routes/index.tsx, tests/server-function/src/routes/is-server-nested.tsx, tests/server-function/src/routes/is-server-toplevel.tsx, tests/server-function/src/routes/node-builtin-nested.tsx, tests/server-function/src/routes/node-builtin-toplevel.tsx, tests/server-function/src/routes/npm-module-nested.tsx, tests/server-function/src/routes/npm-module-toplevel.tsx
=> test(server-functions): add module level directive tests (#1739)

pnpm-lock.yaml
closes #1762 
Delete and `pnpm i`.
The lockfile is very old, and it causing issues.
=> refactor: attempt lockfile remake

package.json, pnpm-lock.yaml
=> chore: update changeset cli

.changeset/rare-socks-jog.md, packages/landing-page/package.json, packages/start/package.json, pnpm-lock.yaml, tests/server-function/package.json
Bump to the new 0.5.2
https://github.com/nksaraf/vinxi/releases/tag/vinxi%400.5.2
Mainly for this fix
- https://github.com/nksaraf/vinxi/pull/458
=> chore: vinxi 0.5.2

.changeset/config.json
Update changeset config due to
- #1750
=> chore: changeset config

packages/start/package.json, pnpm-lock.yaml
bump before we release, so it's as recent as possible.
=> chore: bump server function plugin

examples/pnpm-lock.yaml, examples/with-authjs/package.json
=> chore: fix with-authjs example

.github/workflows/release.yml
The org token is calledn "NPM_PUBLISH_TOKEN"
=> chore: update npm token name

packages/landing-page/package.json, pnpm-lock.yaml
Can this work, or will the manual overrides still be needed?
https://github.com/solidjs/solid-start/pull/1765/commits/824155990764a8ed212b4e12b8b137bd4a203a09
=> chore: use workspace package for landing page

.changeset/blue-geese-scream.md, examples/bare/package.json, examples/basic/package.json, examples/experiments/package.json, examples/hackernews/package.json, examples/notes/package.json, examples/todomvc/package.json, examples/with-auth/package.json, examples/with-authjs/package.json, examples/with-drizzle/package.json, examples/with-mdx/package.json, examples/with-prisma/package.json, examples/with-solid-styled/package.json, examples/with-tailwindcss/package.json, examples/with-tanstack-router/package.json, examples/with-trpc/package.json, examples/with-unocss/package.json, packages/start/package.json, pnpm-lock.yaml
fixes #1749
the actual bug was fixed in DOM-Expressions, landed in newest version of `solid-js` and now we're merely bringing it to the templates.
=> tailwind v4 support

examples/pnpm-lock.yaml, examples/with-tanstack-router/package.json
=> chore: bump start in tanstack example

examples/pnpm-lock.yaml, examples/with-tanstack-router/package.json, examples/with-tanstack-router/src/components/Devtools.tsx, examples/with-tanstack-router/src/routes/__root.tsx
New devtools release (rewritten in solid)
- https://github.com/TanStack/router/pull/3636
Use them in this example
=> chore: add devtools to with-tanstack-router example

.github/workflows/tests.yml, examples/package.json, examples/pnpm-lock.yaml, examples/with-vitest/package.json, package.json, packages/tests/package.json, pnpm-lock.yaml
Another attempt at updating to pnpm v10, now that it's been out for a while as the default `latest`
This appear to be able to resolve some issues, like dependency issues for
- #1847
=> update to pnpm v10

.changeset/thin-geckos-buy.md
=> chore: add changeset

.changeset/yellow-cheetahs-sparkle.md, examples/bare/package.json, examples/basic/package.json, examples/experiments/package.json, examples/hackernews/package.json, examples/notes/package.json, examples/todomvc/package.json, examples/with-auth/package.json, examples/with-authjs/package.json, examples/with-drizzle/package.json, examples/with-mdx/package.json, examples/with-prisma/package.json, examples/with-solid-styled/package.json, examples/with-tailwindcss/package.json, examples/with-tanstack-router/package.json, examples/with-trpc/package.json, examples/with-unocss/package.json, examples/with-vitest/package.json, packages/start/package.json, pnpm-lock.yaml
=> fix: bump vinxi version to latest AND pin @tanstack/server-functions-plugin version

packages/start/package.json, packages/start/src/client/spa/index.tsx, packages/start/src/config/index.ts, packages/start/src/server/spa/StartServer.tsx, packages/start/src/server/spa/handler.ts, packages/start/src/server/spa/index.tsx
=> get spa mode working

.github/workflows/tests.yml, packages/start/package.json, packages/start/src/server/fetchEvent.spec.ts, packages/start/vitest.config.ts, pnpm-lock.yaml
adds Vitest and a few unit tests to existing code prevent regressions and more easily cover new fixes/features
=> cover `fetchEvent` with a few unit tests

packages/start/src/config/index.ts
Adds back an env variable thats required and was set in the vinxi version. Also now its able to be configured.
Also fixes the issue with Solid Notes
=> add server base url
