- README.md
This PR, along with solidui/vite-plugin-solid#12, fixes #4 .
> docs: describe proper monorepo usage

- packages/start/bin.cjs
- packages/start/runtime/devServer.js
The root parameter is defined in the createDevServer function, but it is not used in the CLI. The root option is necessary when working on multi-directory projects where the main folder is not necessarily the solidjs entry.
> Add root option to dev server

- packages/start/bin.cjs
- packages/start/plugin.js
- packages/start/runtime/devServer.js
The plugin always resolves the paths in the root of the project. When the root option is added to the CLI, the plug-in keeps trying to resolve the files in the main folder.
In a multi-folder project, the need for multiple configuration files is common.
> Root option added to plugin and config option added to CLI

- packages/create-solid/templates/app-ts/tsconfig.json
`baseUrl` is a required field if you use `paths`. I am sure a lot of tools will just assume the `tsconfig.json`'s current directory if it's missing, but it's technically required [as part of the spec](https://www.typescriptlang.org/tsconfig#paths) if you use `paths`. IntelliJ for one strictly conforms to this, and it won't work correctly without the `baseUrl`.
I won't be offended if you change `./` to `.`. Most people don't like to put on trailing slashes, but I like to always be explicit when I'm defining a directory!
> Add baseUrl to tsconfig.json

- packages/start/components/Links.tsx
I'm not sure what situation causes this but I've noticed when I have more than 1 page, this function fails because `match` is empty.  Wanted to propose this as a starting point to fix this issue
> Handle empty matches

- packages/start/package.json
solid-start using rollup-route-manifest without rollup
> Missed dependency in solid-start module

- packages/start/plugin.js
on windows, `fileUrl.pathname` for absolute file URLs produces a pathname with leading `/` before the drive letter, like
```
/C:/Users/me/src/solid-next/node_modules/solid-start/plugin.js
```
which is invalid path on windows, see the discussion about this in https://github.com/nodejs/node/issues/23026
Fortunately, `readFileSync` accepts file URLs as well, so there's no need for URL -> path conversion
> fix URL to file path conversion on windows in plugin.js

- examples/basic-ts/package.json
- examples/with-mdx-ts/package.json
- package.json
- packages/start-node/index.js
- packages/start-node/package.json
- packages/start/components/Outlet.tsx
- packages/start/package.json
- packages/start/plugin.js
- packages/start/routes.js
- pnpm-lock.yaml
uses fast-glob (same as vite) to do the route parsing
from the file system. we remove the virtual module for the routes
since it was giving SSR trouble. no API breaking changes, just changes
the internals for how the routes are parsed and loaded
> feat: using our custom route walker using fast-glob

- examples/basic-ts/vite.config.ts
- examples/with-mdx-ts/vite.config.ts
- packages/start/bin.cjs
- packages/start/index.d.ts
- packages/start/package.json
- packages/start/plugin.d.ts
- packages/start/plugin.js
- packages/start/runtime/devServer.js
- pnpm-lock.yaml
The vite plugin currently handles all the parts of the dev and build functionality.. This splits that into smaller modular plugins and overall becomes a preset made of those plugins. We shift the server from an external dev server to just using the vite dev server with our handler. This allows tools like vite-plugin-inspect to work well. 
Adds some additional routes output to the vite URLs when starting a dev server
> infra: split vite plugin to separate parts including dev server

- packages/start/routes.js
Escape periods in route toIdentifier regex, which leaves some routes incorrectly resolved.
Fixes #49
> fix unescaped periods in route toIdentifier regex

- packages/start/bin.cjs
- packages/start/routes.js
1. On windows, node binaries are usually started using cmd or powershell scripts, which can't be spawned without `shell: true`
2. In routes.js, the intent is to import file using its absolute path. Technically correct way for this is to use file URLs, but vite resolver does not support `file:///` URLs. Also, vite does not seem to recognize absolute paths in windows format. Using absolute posix paths is the only way I could find to get this to work.
> fix ENOENT when spawning vite and imports path resolution on windows

- packages/start/components/StartContext.tsx
```ts
export const StartContext = createContext<{
manifest?: Record<string, any>;
context?: Record<string, any>;
}>({});
```
now matches manifest & context types in:
https://github.com/solidjs/solid-start/blob/main/examples/basic-ts/src/entry-server.tsx
Fixes https://github.com/solidjs/solid-start/issues/52
> StartContext: generic types of manifest & context match entryServer.ts

- packages/start/plugin.js
this uses `normalizedPath` from vite to avoid mismatch with file paths which are normalized by vite.
it makes vite an actual runtime dependency, but I think it's ok
to leave it as it is - both dev an peer dependency
> fix path resolution for manifest on windows (fix #60)

- packages/start/server/babel.js
This PR updates the function used to create hashes for inline server modules in production builds.
I ran into errors building for production as the current hash function returns numbers (often negative) which later causes `path.join` to fail. The new function uses Node's crypto lib and the shake256 algorithm which lets us control the output length.
> Use crypto func for ISM hashes in prod

- packages/create-solid/README.md
It looks like the README had some copy pasta issues as the README referred to Next.js in many locations.
> chore: remove invalid Next.js references

- packages/start-cloudflare-workers/package.json
- packages/start-netlify/package.json
- packages/start-node/package.json
- packages/start-static/package.json
- packages/start-vercel/package.json
- packages/start/package.json
- pnpm-lock.yaml
Use the `next` tag instead of `*` to correctly resolve the latest version and avoid multiple versions of solid-start-node and solid-start.
> chore: use solid-start-node@next & solid-start@next fix #85

- packages/start-static/index.js
This patch makes the static adapter get the names of the path components for its input files from the configuration passed to the Vite plugin instead of hard-coding `src` and `routes`.
> Static adapter: Get path components from Vite config

- packages/start-vercel/index.js
When trying to build using `solid-start-vercel`, it throws an error due to missing `resolve` import.
Error message:
```./node_modules/solid-start-vercel/index.js:26
input: resolve(join(config.root, appRoot, `entry-client`)),
^
ReferenceError: resolve is not defined
at Object.build (./node_modules/solid-start-vercel/index.js:26:20)
at ./node_modules/.pnpm/solid-start@0.1.0-alpha.69_dd0a6a10e5f7b16d27d7286030fa2e9f/node_modules/solid-start/bin.cjs:39:13
```
The build goes successfully when adding the missing resolve import.
> Missing resolve from path import

- packages/start-cloudflare-workers/package.json
- packages/start-netlify/package.json
- packages/start-node/package.json
- packages/start-static/package.json
- packages/start-vercel/package.json
- packages/start/plugin.js
Added zero-configuration detection for adapters.
Now the only thing needed to get started with solid is to drop off `solid()` and install the adapter you need. 🚀
By looking through the current directory for node_modules, then if it's not found, keep looking up the path for the directory. When node_modules are found, look for any directory starting with "solid-start-", ignore the default "solid-start-node"; Then, in case a package is found, apply that name and default to "solid-start-node".
> Added auto detection for adapters

- examples/with-tailwindcss/src/root.tsx
- examples/with-vitest/src/root.tsx
As per [Discord discussion](https://discordapp.com/channels/722131463138705510/910635844119982080/971093152570175488), this adds ErrorBoundary and Suspense to the tailwind and vitest examples and therefore makes these examples consistent with the changes in 67eaa63cfbcb0e94d04617e76eeed354cab017ed.
> add ErrorBoundary and Suspense wrappers to tailwind and vitest examples

- packages/start/routes.js
I noticed that the vite server was restarting every time I edited a file. I tracked it down to the chokidar file watcher inside `routes.js` giving back a windows style path containing backslashes, while the existing path inside the `routes` object are url/posix style paths only containing forward slashes.
This is a simple fix that converts the file path to a posix file path.
> fix windows path handling

- packages/start/plugin.js
IS:
Changing files with routeData do trigger full server restarts. The old router file watcher is not closed during the restart.
https://user-images.githubusercontent.com/4012401/167722661-44bb561d-aa9d-4ef3-a8ed-2d2e9e180faf.mp4
SHOULD:
A server restart should close the old router file watcher since a new one is created.
https://user-images.githubusercontent.com/4012401/167722694-3a00cef5-53f4-44a7-b3f6-aa1c38ddc413.mp4
> close router file watcher before server restarts

- packages/start/routes.js
Fix #107 
An earlier commit by @ryansolid partially fixed the issue, but it only worked for the nested index (index/index.tsx) and not for any other pages e.g. (index/about.tsx)
> fix index nested routes

- packages/start-static/index.js
Running the build tasks in parallel fails when the vite.config is a `.ts` file. This avoids the missing config file error when generating the output.
Vite generates a `vite.config.ts.js` when the project has `"type": "module"` set in the `package.json` which seems to fail when multiple build tasks are running:
https://github.com/vitejs/vite/blob/main/packages/vite/src/node/config.ts#L728
> fix: run build in sequence

- packages/start/routes.js
If you have the following path:
`[foo]/[bar].tsx`
Before:
`http://localhost:3000/:foo]/[bar`
After:
`http://localhost:3000/:foo/:bar `
> fix path regex for routes with more than 1 param

- packages/start/plugin.js
The babel transform for `createServerResource` was missing for .data files.
> fix createServerResource inside .data files

- packages/start/plugin.js
- packages/start/server/routeDataHmr.js
Currently if you have a page that exports a `routeData` function like this:
```javascript
export function routeData() {}
export default function Home() {
return <div></div>;
}
```
the page will reload whenever you make a change to the component.
This PR fixes that by adding a new babel plugin for ?data modules. The plugin creates a hash of the whole source code of the module and then injects some HMR code into the module to compare the hashes, if the hashes don't match the page is reloaded.
I left the code in template form so it's easier to review and tweak for now, but it can be converted into babel-types function calls like the other plugins for some extra performance.
> fix hmr for pages with routeData

- packages/start/server/server-functions/types.ts
Currently the `ServerFn` type does not reflect the fact that the function returned by it returns a `Promise`.
The user may or may not use an async function with `server`.
```typescript
server(async () => {
return 33
})()
```
```typescript
server(() => {
return 33
})()
```
Simply wrapping the return type in `Promise` could result in a nested Promise type like `Promise<Promise<number>>`.
`Awaited` is used to erase the `Promise` (whether there is one or not) and then the result is wrapped in `Promise` to reflect that the function returned by  `server` returns a `Promise`.
> types: wrap ServerFn return type in promise

- packages/start/plugin.js
- packages/start/root/Links.tsx
- packages/start/routes.js
- test/link-test.ts
Fixes #171 
Previously only link tags for the topmost routes were being added to the document. Now all link tags for the ancestors routes will be added. This fixes a CSS flashing issue during prod SSR for nested routes.
A check for index nested routes was also added to correctly match the manifest key, this fixes an issue where the CSS was not getting loaded at all during prod SSR for index nested routes.
> fix link tags for nested routes

- examples/bare/src/entry-client.tsx
- examples/bare/src/root.tsx
- examples/bare/src/routes/index.tsx
- examples/bare/vite.config.ts
- packages/start-node/index.js
- packages/start/bin.cjs
- packages/start/dev/create-index-html.js
- packages/start/dev/server.js
- packages/start/entry-client/index.tsx
- packages/start/entry-client/mount.ts
- packages/start/package.json
- packages/start/plugin.js
- packages/start/root/Document.tsx
- packages/start/root/FileRoutes.tsx
- packages/start/root/InlineStyles.tsx
- packages/start/root/Scripts.tsx
- packages/start/root/index.tsx
- packages/start/server/types.tsx
- pnpm-lock.yaml
- test/action-test.ts
- test/spa-test.ts
- test/template/src/entry-client.tsx
- test/template/src/root.tsx
1. We can use the setup we have with SSR by using the same root and entry-client, we ignore the entry-server in prod.. but we use it at build time to construct a shell for the SPA. The shell will include all the content upto the file routes such that it can include api calls that could be cached at build time (if desired, of course we will need a way to disable this feature so everything is SPA, including index.html)
> ssr and spa becomes a one flip switch

- packages/start/root/Scripts.tsx
Since on windows the URL was starting with `C:\` the browser was treating it as a local file request.
This PR simply adds `/@fs/` in front of the absolute file path.
This will create URLs like the following:
Windows
`/@fs/C:\...\examples\bare\src\entry-client.tsx`
Linux
`/@fs//home/.../examples/bare/src/entry-client.tsx`
The vite dev server seems to handle the extra slash in the Linux URL just fine and the browser seems to take care of converting the backslashes to slashes.
I tested this on Windows and WSL Ubuntu, with an entry-client and without.
> fix entry-client url on Windows

- packages/start-static/index.js
Fixed a problem in which backslashes were used in the path when using `solid-start-static` on windows and it did not build properly.
> Fixed path resolution when using windows

- packages/start/dev/server.js
The page would always reload after changing the JSX inside a page. This shouldn't happen because `vite-plugin-solid` injects `solid-refresh` in every component. 
This was caused by there being 2 different `ModuleNode` for the same module. This in turn caused the `isSelfAccepting` property to get set on the duplicate module instead of the original one.
This issue couldn't be replicated by directly running one of the example in the `solid-start` repo because `solid-refresh` doesn't apply to files with `node_modules` in their path but since the examples use `pnpm link` the files in the `solid-start` package had a path without `node_modules` in it and were getting `solid-refresh` applied to them like `FileRoutes` which is what imported the pages and prevented the reload from happening.
To …
> Fix HMR issue caused by the collection of styles during dev

- packages/start-cloudflare-pages/entry.js
- When refreshing the page currently `entry.js` does not match response 304 and will fail to load assets until a subsequent refresh.
- I've now added `(resp.status === 200 || 304)` so if nothing has changed on the page it will now return assets on page reload.
> Fixed refresh bug as it would never match response 304 Not Modified

- README.md
For any folks using Yarn 2+, the `nohoist` option no longer works :(. I was able to get things working via the config option described in this PR.
> add note about yarn 2 hoisting

- packages/start-netlify/README.md
Was extremely confused by this for a quick second. If you copy/paste the `vite.config.js` file from the Netlify adapter README you'll get a build error because it's not importing `defineConfig`.
> Add defineConfig to Netlify Vite config

- examples/bare/README.md
- examples/durable-objects-websocket/README.md
- examples/hackernews/README.md
- examples/todomvc/README.md
- examples/with-auth/README.md
- examples/with-mdx/README.md
- examples/with-solid-styled/README.md
- examples/with-tailwindcss/README.md
- examples/with-vitest/README.md
- test/template/README.md
I noticed all but one of the example README's had the command `node build` written where it should be `npm start` instead.
I also modified the one instance of `npm run start` to just `npm start` since you don't need to include `run` when using `start`. As far as I can tell there's [no real difference between the two](https://stackoverflow.com/questions/51358235/difference-between-npm-start-and-npm-run-start) so the more concise option seems preferable to me.
> docs: Fix start command in example READMEs

- packages/start-cloudflare-pages/index.js
- packages/start-cloudflare-workers/entry.js
- packages/start-deno/entry.js
- packages/start-netlify/index.js
- packages/start-node/server.js
- packages/start-vercel/index.js
Files in the [`/assets` dir](https://vitejs.dev/config/build-options.html#build-assetsdir) get a [content hash from Vite/Rollup](https://github.com/vitejs/vite/blob/07d3fbd21e6b63a12997d201a2deb5b2f2129882/packages/vite/src/node/build.ts#L552) by default. Because they have a content hash, the deploy adapters can give these files a `Cache-Control` header of `public, immutable, max-age=31536000` which will allow browsers to cache the files without needing to ping the server again.
This can speed up repeating loadings of the site deployment and also cut down on HTTP requests, which could help stretch the free quota or reduce costs for various serverless site providers.
I would like to have this feature in the Cloudflare Workers adapter, which I am currently using, so I tested this feature …
> Add cache control header for immutable static assets

- docs/core-concepts/api-routes.md
> Fix typo in api-routes page

- test/multi-action-test.ts
Currently, the last case is failing, it's exactly what we talked about on discord. We can easily remove/skip this test if we don't want to support this case.
I decided to use cookies to easily control the response success/error from playwright testa, as well as the delay for testing responses coming out of order or with delay
> Add tests for multi action

- examples/with-tailwindcss/src/routes/[...404].tsx
In the Tailwind example, an `<A>` component is used for an external link. Changed that to a native `<a>` element.
> example: use native `<a>` element

- examples/with-tailwindcss/tailwind.config.cjs
Adds type annotation to `tailwind.config.js`, see [here](https://tailwindcss.com/docs/configuration#type-script-types).
> example: enable type support for tailwind config

- packages/start/node/globals.js
Since Node 19, the [`crypto` global has been redefined to the WebCrypto object](https://nodejs.org/en/blog/announcements/v19-release-announce/#stable-webcrypto), and the [current globals.js](https://github.com/solidjs/solid-start/commit/fe6e4405c8d0205f95b1232f10c3290765cd159d) code errors as it can't assign to a key that's already a getter.
This PR checks if the `crypto` global is already the WebCrypto object first before redefining it. An alternative approach is to get `process.version` and verify the major version before assigning `globalThis.crypto`.
> fix: webcrypto global under Node 19 runtime

- examples/movies/src/routes/layout.module.scss
- examples/movies/src/routes/movie/[movieId]/layout.module.scss
- examples/movies/src/routes/movie/[movieId]/layout.tsx
I just did some small css improvements to:
- make the logo on mobile not touch the border of the nav
- make the menu in the movie details page not touch the border of the page and space the menu options out
I've checked and the Desktop design is still intact.
BEFORE & AFTER
Logo Before| Logo After
:-------------------------:|:-------------------------:
Menu Before | Menu After
:-------------------------:|:-------------------------:
> Small css improvements

- docs/core-concepts/api-routes.md
After creating a new solid-start project (bare/ts/no-ssr), installing tRPC and following the tRPC example in the docs, I ended up with a non-working state.
Calling proxy.hello.query() results in a 404.
Let's update it.
- Replace createTRPCClient and createTRPCClientProxy with createTRPCProxyClient
- Move type AppRouter to lib/router.ts
- Use a catchall route
The tRPC client calls `/api/trpc/hello` which does not get handled by `routes/api/trpc.ts`.
Should the use of a catchall route be mentioned or is it enough to change filename to `routes/api/trpc/[...].ts`?
> Fix trpc example in docs

- docs/core-concepts/routing.md
Saw that we were missing these so I wanted to add them. There is probably a better naming for "Renaming Index" so I'm open to any suggestion. 
Also closes #425
> docs: Add doc for Route Groups and Index Renaming

- docs/core-concepts/routing.md
"For these use cases you can use an imperative `navigate` function that you can **get** by calling `useNavigate()`."
Not sure if that needs to be expanded upon to mention that the `navigate` function is the return value of the `useNavigate` primitive/hook.
> Add missing word to routing docs

- examples/with-prisma/src/routes/login.tsx
The app was breaking because we needed to pass `db` as well as `request` object to the getUser function called in `login.tsx`.
I updated the file and now the app starts without any bug!
> fix(example:with-prisma): Fixed a breaking bug in with-prisma example

- examples/with-prisma/src/routes/login.tsx
- examples/with-prisma/vite.config.ts
Example does not work.
- Call to `getUser` in login.tsx is missing db as first argument
- Production build fails to start without externalizing `@prisma/client`
Trying to start production build without externalizing the prisma client will result in:
> Fix prisma example

- examples/with-websocket/package.json
Added missing dependency for `with-websocket` example.
Related to https://github.com/solidjs/solid-start/issues/417
> Fix `with-websocket` Example

- packages/start-vercel/README.md
- packages/start-vercel/entry-prerender.js
- packages/start-vercel/index.js
This allows us to use vercel's ISR and [prerender functions](https://vercel.com/docs/build-output-api/v3#vercel-primitives/prerender-functions).
To enable ISR/Prerender, pass in the prerender function.
```js
import { defineConfig } from "vite"
import solid from "solid-start/vite"
import vercel from "solid-start-vercel"
export default defineConfig({
plugins: [
solid({
ssr: true,
adapter: vercel({
prerender: true,
}),
}),
],
})
```
You can also set the `expiration` time and/or the `bypassToken`. 
(`expiration` defaults to `false`, meaning it won't expire)
```js
import { defineConfig } from "vite"
import solid from "solid-start/vite"
import vercel from "solid-start-vercel"
export default defineConfig({
plugins: [
solid({
ssr: true,
adapter: vercel({
prerender: {
expiration: 60,
bypassToken: …
```
> Allow isr/prerender on Vercel

- docs/core-concepts/api-routes.md
Added a working example of GraphQL implementation in the docs under the API routes section
> add to api-routes docs: graphql api implementation example

- packages/start/vite/plugin.js
https://github.com/solidjs/solid-start/issues/495
needed to update the regex
> fix: islands only work with double quote imports

- packages/start/bin.cjs
Also while I'm here. Do you think we should pass original NODE_OPTIONS, like
```ts
NODE_OPTIONS: `--experimental-vm-modules ${inspect ? "--inspect" : ''} ${process.env.NODE_OPTIONS || ''}`
```
?
> Undefined when converted to string returns "undefined"

- README.md
- docs/getting-started/project-setup.mdx
- examples/bare/README.md
- examples/hackernews/README.md
- examples/todomvc/README.md
- examples/with-auth/README.md
- examples/with-mdx/README.md
- examples/with-prisma/README.md
- examples/with-solid-styled/README.md
- examples/with-tailwindcss/README.md
- examples/with-vitest/README.md
- examples/with-websocket/README.md
- packages/create-solid/README.md
- packages/start/README.md
- test/template/README.md
`npm init` uses a local cached package if existed.
So an outdated version could be called with `npm init solid`.
This PR changes all `npm init solid` to `npm init solid@latest` to prevent this. (pnpm always fetches the latest version and doesn't need `@latest`.)
> Add `@latest` to `npm init solid`

- packages/start/vite/plugin.js
This PR is a minor refactoring.
Vite 3+ has a [`appType` option](https://vitejs.dev/config/shared-options.html#apptype) that will control whether HTML related middlewares should be injected.
By setting `appType: 'custom'`, HTML middlewares won't be injected.
> Use `appType: 'custom'`

- examples/with-tailwindcss/src/root.tsx
- examples/with-tailwindcss/src/routes/about.tsx
* Native `<A>` was being used for linking solidjs.com on `/about`, changed it to native `<a>`
* Navbar addition
> example: using native `<a>` for external links, updated navbar (tailwind example)

- package.json
- pnpm-lock.yaml
Fixes the docs:build script used to deploy the docs site. The error occurring was twoslash expects type definitions for modules imported in code examples. `docs/core-concepts/api-routes.md` includes an example of exposing a GraphQL API, and imports from the `graphql` package.
> Fix `pnpm run docs:build`

- packages/start/entry-client/mount.tsx
- packages/start/vite/plugin.d.ts
Changing the name of the property attached to the window in the global typescript scope from DEBUG to SOLID_DEBUG to prevent naming conflicts with other NPM packages.
> Debug Naming Conflict

- docs/api/createRouteData.md
I didn't realize until #562 that `key`s in `createRouteData` and `createServerData$` were reactive. This PR documents that.
> Add example of refetching based on a query parameter

- packages/start/vite/plugin.js
Respect Vite's [options.envDir](https://vitejs.dev/config/shared-options.html#envdir) when loading Solid Start's environment variables.
When working inside a monorepo it sometimes makes sense to be able to put the `.env` file in the root of the workspace and share it between all of the projects in subfolders. This allows you to do that.
> Respect Vite envDir when loading environment vars

- .stackblitzrc
Fixes solidjs/solid-start#550 and stackblitz/core#2226
> Add chmod +x to .stackblitzrc

- packages/create-solid/cli/index.js
hello,
this PR will add package manager detection on `pnpm create solid` or `yarn create solid` to make it just a little nicer
example:
```
Next steps:
1: cd my-project
2: pnpm install
3: pnpm run dev -- --open
```
note: inspiration and code taken from [create-t3-app](https://github.com/t3-oss/create-t3-app/blob/62e86c47cc2dafba634230b13aacfed61588c376/cli/src/utils/getUserPkgManager.ts)
> add package manager detection on create-solid

- packages/create-solid/cli/index.js
tested manually by running a bin file produced by `pnpm --filter create-solid build`
> Make TypeScript the default when running create-solid (#421)

- examples/bare/package.json
- examples/bare/required-user-files.d.ts
- examples/hackernews/package.json
- examples/hackernews/required-user-files.d.ts
- examples/todomvc/package.json
- examples/todomvc/required-user-files.d.ts
- examples/with-auth/package.json
- examples/with-auth/required-user-files.d.ts
- packages/create-solid/cli/index.js
- pnpm-lock.yaml
Running `tsc --noEmit` for any created examples causes type errors.
I resolve these issues errors for a subset of examples by adding missing devDependencies and `declare module` files.
Please let me know what you think approach:
* Could this be fixed for transitive dependencies instead? (for example by changing solid-start-node's package.json)
* Adding extra dependencies makes `pnpm` run slower(but could fix potential LSP server issues)
* Should I create a corresponding tracking bug?
* I'm not sure what is the right way of updating `pnpm-lock.yaml`
> Fix typescript dependencies issues for examples

- docs/api/A.md
Fix for #599. Doc based on solid app router doc.
> docs: Fix documentation for <A> 'replace' prop

- examples/with-vitest/jest.config.js
- examples/with-vitest/package.json
- examples/with-vitest/setupVitest.js
- examples/with-vitest/vite.config.ts
- examples/with-vitest/vitest.config.ts
- packages/start/vite/plugin.js
- pnpm-lock.yaml
Add some commands to `package.json`:
- pnpm test: "vitest run",
- pnpm test-watch: "vitest",
- pnpm test-ui: "vitest --ui",
- pnpm coverage: "vitest run --coverage"
I fixed a bug in Solid's vite plugin, which prevented Vitest --ui from starting.
`vite.resolvedUrls` is always null when running Vitest --ui server. So I added a check to that.
I updated the template so that is works out of the box.
And move test config, to `vitest.config.ts`instead of of `vite.config.ts`. This avoids configuration conflicts as some have reported here and there.
Hope this helps :-)
> Fix and improve with-vitest template

- packages/start/bin.cjs
This PR creates `routes` command in solid-start cli.
This is similar to remix cli `route --json` command.
https://github.com/remix-run/remix/blob/main/packages/remix-dev/cli/run.ts#LL26C8-L26C8
It allows you to see the generated page routes.
In an example run of `solid-start routes` of some solid-start project with simple routes, The printed result can be
```
[
{
id: '/index',
path: '/',
componentPath: 'src/routes/index.tsx',
dataPath: 'src/routes/index.tsx?data'
},
{ id: '/test', path: '/test', componentPath: 'src/routes/test.tsx' },
{
id: '/api/something/(other)',
path: '/api/something',
componentPath: 'src/routes/api/something/(other).tsx'
},
{
id: '/api/something/[id]',
path: '/api/something/:id',
componentPath: 'src/routes/api/something/[id].tsx'
}
]
```
I'm not sure it's useful.
I …
> add solid-start routes command

- docs/api/root.md
Even though the links are working on GitHub, they would create broken links in https://start.solidjs.com/api/root. This PR fixes it.
> docs(root): fix api links

- packages/start-vercel/index.js
This creates a seperate serverless function `api.func` to handle API routes. 
An effect of this is fixing https://github.com/solidjs/solid-start/issues/612
Build output
```
.vercel
├── output
│  ├── config.json
│  ├── functions
│  │  ├── api.func
│  │  │  └── index.js
│  │  └── render.func
│  │     └── index.js
```
Config
```ts
{
"version": 3,
"routes": [
...
// Add route for api handler
{
"src": "/api/hello",
"dest": "/api"
},
{
"src": "/.*",
"dest": "/render"
}
]
}
```
Not sure if this is the best approach, but would at least make ISR work with API routes. We could limit it to only be done when prerender is enabled, but I think it should be fine even when it is not enabled.
If there is a way to get a server output with only API routes it would make more sense (and without API routes for …
> split vercel api routes function

- packages/start-aws/index.mjs
- packages/start-cloudflare-pages/index.js
- packages/start-cloudflare-workers/index.js
- packages/start-deno/index.js
- packages/start-netlify/index.js
- packages/start-node/index.js
- packages/start-static/index.js
- packages/start-vercel/index.js
Fixes #623 
Vite has an option to inject configuration parameters to @rollup/plugin-commonjs in the vite.config.ts like this:
```ts
import { defineConfig } from "vite";
export default defineConfig({
build: {
**commonjsOptions: {}**
},
});
```
Unfortunately that doesn't work in solid-start, because the node adapter takes control over the 3 default rollup plugins like this ( separate issue #628 ):
https://github.com/solidjs/solid-start/blob/df206edb975de4941e368c92ec9e25c825592005/packages/start-node/index.js#L45-L52
Arguably it would be ideal to have a way of injecting the parameters from vite.config.ts in here, but as long as there is no such way, the way to adjust the parameters of commonjs plugin for users of SolidStart, it's wisest to use the safest default option that is least likely …
> Use safest defaults for @rollup/plugin-commonjs

- packages/start/package.json
- packages/start/vite/plugin.js
- pnpm-lock.yaml
Currently package/start depend on two vite-plugin-inspect packages (it's the same [github repo](https://github.com/antfu/vite-plugin-inspect)):
- @vinxi/vite-plugin-inspect
- vite-plugin-inspect (This is the newer npm package)
This PR simplifies things by:
- removing @vinxi/vite-plugin-inspect
- updating vite-plugin-inspect from 0.6.1 to 0.7.12 (Vite 4 compatible since ^[0.7.10](https://github.com/antfu/vite-plugin-inspect/releases/tag/v0.7.10))
> Replace @vinxi/vite-plugin-inspect with vite-plugin-inspect

- packages/start-aws/index.mjs
- packages/start-cloudflare-pages/index.js
- packages/start-cloudflare-workers/index.js
- packages/start-deno/index.js
- packages/start-netlify/index.js
- packages/start-node/index.js
- packages/start-static/index.js
- packages/start-vercel/index.js
Fixes #628 
in adapters, this pr changes
`common({ strictRequires: true })`
to:
`common({ strictRequires: true, ...config.build.commonjsOptions })`
making the vite.config.ts option functional
> Inject vite.config build.commonjsOptions into adapters

- packages/start/api/index.ts
- packages/start/fs-router/path-utils.js
- test/api-routes-test.ts
This PR adds support for optional params to the file system routing.
The syntax chosen is `[[param]]`, the first set of square brackets indicate that it is a parameter and the second set indicate that it is optional.
This syntax was chosen because `?` is not a valid character in filenames on Windows.
> **_src/routes/[[lang]]/blog/test.tsx_**
| path | params |
| ------------- | ------------- |
| /blog/test  | {} |
| /en/blog/test  | { lang: "en" }  |
> Add support for optional params

- packages/start/data/Form.tsx
As implemented, if you place an SVG inside a submit button in a progressively-enhanced form, and then click the SVG instead of any other part of the button, `clickedButtonRef` fails to be set. Thus, when submitting the form, the target is the form rather than the button, and any `name` / `value` attributes on the button are ignored when constructing the `FormData` to submit.
I tested with JavaScript disabled and clicking the icon inside the button _does_ submit that button's `name`/`value` attributes, so I think the progressive enhancement implementation should replicate this.
The current workaround is to set `pointer-events: none;` on the SVG element inside the submit button, but this is not necessary with JavaScript disabled.
> Handle clickedButtonRef when clicked element is an SVGElement

- packages/start/data/createRouteAction.tsx
The props for the `Form` returned from `createRouteAction` accept an `onSubmission` prop, but it is always overridden.
My use-case is that I want to track the last successfully submitted `FormData`. If there is another way to do this I'm open to alternatives. We could also implement another prop for this if one doesn't exist. The problem with the `result` signal is that it gets set to `undefined` with every submission, resulting in the need to memoize the non-`undefined` values, which is easy to do, just not ergonomic.
Here are some alternative solutions to the root problem of a prop `onSubmission` being declared that isn't called that we could implement, depending on what behavior is ultimately desired by `solid-start`:
1. We can call both the internal `submit` and `props.onSubmission` …
> Omit action and onSubmission props from createRouteAction Form

- package.json
- pnpm-lock.yaml
Currently `"ts-jest-template-solid"` requires `"vite":"^3.1.8"` if I'll try to add solid-start (which is obviously required for routing and other necessities)
bump `vite` to 4.0.4
> Bump vite dependency

- pnpm-lock.yaml
- test/package.json
Part of the vite 4 support #660 
Vitest has vite 4 support since 0.25
All 87 tests still pass.
> Bump vitest from 0.20.x to 0.27.x for Vite 4 compat

- packages/start/server/server-functions/babel.js
- packages/start/server/server-functions/browser.ts
- packages/start/server/server-functions/server.ts
- packages/start/server/server-functions/types.ts
- packages/start/server/serverResource.js
Server functions created using the server resource primitives ( `createServerData$`, `createServerAction$`, `createServerMultiAction$` ) will now be differentiated from regular `server$` calls.
> explicitly handle serverResource server functions

- docs.root.tsx
Quick grammar correction for `og:site_name`, noticed when shared doc's link to another people.
> fix og:site_name grammar

- test/css-link-test.ts
Part of #660 
In Vite 4 apparently a dot is swapped with a dash in the css path - and that doesn't match the RegExp used to match css files causing all css-link-tests to fail.
This PR makes the tests find on files with both dots and dashes.
If vite 4 also breaks the actual loading of the css files is not clear to me, and it will have to be resolved separately.
**Vite 4**
[
'/assets/entry-client-a5369801.css',
'/assets/login-1d9a1004.css',
'/assets/(auth)-cf9318ab.css'
]
**Vite 3**
[
'/assets/entry-client.a5369801.css',
'/assets/login.1d9a1004.css',
'/assets/(auth).cf9318ab.css'
]
> Make css link tests compatible with Vite 4 css paths

- packages/create-solid/cli/index.js
prompt user for target if they didn't supply one through argv
**Disclaimer:** I couldn't get the CLI to run locally (`pnpm build` errors, even tried `node cli/index.js` and that errored too). 
Not sure how you build or run this CLI but this should do it.
ref:
> feat(create-solid): prompt target if not supplied through args

- packages/start/data/createRouteAction.tsx
#682 
The createRouteAction.tsx, is already calling handleRefetch() when the response is not instance of Response interface.
```tsx
.then(async data => {
if (reqId === count) {
if (data instanceof Response) {
await handleResponse(data, navigate, options);
} else await handleRefetch(data as any[], options);
if (!data || isRedirectResponse(data)) setInput(undefined);
else setResult({ data });
}
return data;
})
.catch(async e => {
if (reqId === count) {
if (e instanceof Response) {
await handleResponse(e, navigate, options);
}
if (!isRedirectResponse(e)) {
setResult({ error: e });
} else setInput(undefined);
}
```
When it is instance of Response, the handleResponse should call handleRefetch when it is not a redirect. I don't think it make sense to invalidate query only when is happening a …
> feat: call handleRefetch() when the response is not a redirect

- pnpm-lock.yaml
- test/package.json
Related to #660 
All deps except vite and @playwright/test are bumped to their latest.
It seems like @playwright/test breaks the spa-rendering test when bumping the minor version further (not aligning to semver), and looking into that is next step after this as it's the same unit test that vite 4 breaks.
> Bump deps for tests

- packages/start-vercel/index.js
- packages/start-vercel/package.json
- pnpm-lock.yaml
This is a companion/alternative for Vercel pr to #644. [Discord discussion](https://discord.com/channels/722131463138705510/1063330181793714246)
Vercel functions expect all required files to be within the `*.func` folder while normally this is done automatically with the build process but some files can't be bundled notably prisma's `*engine.node` and `schema.prisma` files
in order to do this we use vercels nft (node file trace) package which is used is used internally by next. unlike next we can't just include a [[file].js.nft.json](https://vercel.com/docs/file-system-api/v2#configuration/bundling) file along side the handler due to it not being supported in their [Build Output v3](https://vercel.com/docs/build-output-api/v3). So what we have to do is recreate the folder structure of the …
> feat(solid-start-vercel): use @vercel/nft to include un-bundable dependancies

- .github/workflows/test.yml
- pnpm-lock.yaml
- test/package.json
@playwright/test breaks the spa-test  from version 1.26.0 ( same as Vite 4 does #674 ), so this bumps it to the latest version before that.
We bumping to 1.26 and beyond, this happens for both index.html and root.tsx:
> Bump playwright to 1.25.2

- examples/with-solid-styled/package.json
- examples/with-solid-styled/vite.config.ts
- pnpm-lock.yaml
Modifies the `solid-styled` example to use the new babel plugin.
https://github.com/lxsmnsyc/solid-styled/tree/main#babel
~~The `solid-styled` example seems to be broken (no styles get applied). It's fixable by adding the [vite plugin](https://github.com/lxsmnsyc/solid-styled/tree/main/packages/vite).~~
> updates examples/with-solid-styled babel config

- packages/start-vercel/index.d.ts
- packages/start-vercel/index.js
- packages/start-vercel/package.json
This will remove the ugly ```@ts-ignore``` when using solid-start-vercel
closes https://github.com/solidjs/solid-start/issues/716
> types: add types for the vercel adapter

- packages/start-static/index.js
I got caught in the pitfall of thinking that solid start SSR option is for runtime SSR, so I disabled it when building a SSG app with the static adapter and got the error `getStaticHTML is not a function`.
This PR will throw a more descriptive error when building with static adapter and SSR disabled.
this is PR is related to the issue https://github.com/solidjs/solid-start/issues/325
> throw an error when building with solid start static when ssr is disabled

- packages/start/entry-server/StartServer.tsx
Fixes #731.
Unsure if this is the preferred way to solve this problem, as I don't have much knowledge in this codebase. I tested by making this change in the `node_modules` of a project I'm working on, but I was unable to follow the steps in the `CONTRIBUTING.md` to test.
More than happy to test, but currently getting:
```
~/github/solid-start$ pnpm --filter example-hackernews run dev
> example-hackernews@ dev github/solid-start/examples/hackernews
> solid-start dev
solid-start dev 
version  0.2.20
failed to load config from github/solid-start/examples/hackernews/vite.config.ts
node:internal/errors:478
ErrorCaptureStackTrace(err);
^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /github/solid-start/packages/start/fs-router/fileRoutesImport.ts
at new NodeError …
```
> fix: always render doctype

- packages/start-netlify/index.js
- packages/start-vercel/index.js
related #739 
Its possible to have packages that can't be processed for a server bundle ex `monaco-editor`. you can tell vite to not process this with ssr.external config value but for vercel and netlify this is not forwarded to the final build.. normally we wan't to bundle everything that we can butthere should be a escape hatch for these cases which the node adapter already does.
if the file is truely needed it will be copied during the final parts of the build process to where it is needed unprocessed by rollup and vite
- #702 for vercel
- Netlify does this automatically in their ci platform with [zip-it-and-ship-it](https://github.com/netlify/zip-it-and-ship-it) 
this also works with #744 to remove client only imports with `unstable_clientOnly`
> Vercel & Netlify forward ssr.external to rollup build

- packages/start/entry-client/StartClient.tsx
- fixes https://github.com/solidjs/solid-start/issues/397
- allows us to use github pages with the static adapter.
> fix: use base path in client router

- examples/todomvc/package.json
- pnpm-lock.yaml
Solid and associated dependencies should be added to prod dependencies and not dev dependencies. The other examples are correctly setup and this seemed to be the only incorrectly setup one
> fix(examples/todomvc): move packages to dependencies

- packages/start/bin.cjs
related #739 
by not allowing vite to split dynamic imports rollup is unable to do any dead code elimination... with the current setup vite will always include dynamic imports even if they are never available like clientOnly in ssr. also vite's default output in esm so setting it to esm its redundant
How does this effect adapters?
- For adapters that use file output nothing is changed it will still output a single file
- For adapters that use dir output rollup will dump the extra files in the output folder which is just dist in all cases currently and from my testing the frameworks had no issue picking up the extra files.
to confirm that client only is removed i have a example repo here https://github.com/arbassett/solid-start-clientOnly-fix with the patch and committed dist dir to show …
> Allow vite to split dynamic imports to multiple files

- packages/start-netlify/entry-edge.js
- packages/start-netlify/entry.js
Netlify exposes certain information that is useful to the handler via context. It's request function provides a separate context value that was never added to the handler.
This PR ensures that it is apart of it so the user can gain access to things like the geolocation data provided by Edge Functions: https://edge-functions-examples.netlify.app/example/geolocation
> start-netlify: Add context to request handler

- docs/core-concepts/head-and-metadata.md
Hello, I notice that the `props` param is missing in this example on the `MySiteTitle` function:
```tsx
export default function MySiteTitle() {
return <Title>{props.children} | My Site</Title>;
}
```
This is the first time I read a SolidJS related doc, so I was not 100% sure that the props came as param like React. But I tested it in the code sandbox and it throw an error without it, so I open this PR. This will avoid confusion with new devs like me.
Nice project by the way!
> Add missing props param in the MySiteTitle example

- packages/create-solid/cli/index.js
Adds `.env` patterns to `.gitignore` to avoid new Solid Start projects from committing their environment variables accidentally.
Thought here is `.env` in addition to `.env*.local` which will cover a variety of uses intended only for local environments.
More background behind thought on specific additions on Issue.
Fixes:  #763
> Add .env to .gitignore

- packages/start-cloudflare-pages/entry.js
- packages/start-cloudflare-pages/index.js
- packages/start-cloudflare-workers/entry.js
- packages/start-cloudflare-workers/index.js
- packages/start-deno/entry.js
- packages/start-deno/index.js
- packages/start-netlify/entry.js
- packages/start-netlify/index.js
- packages/start-node/entry.js
- packages/start-node/index.js
- packages/start-static/entry.js
- packages/start-static/index.js
Since dynamic imports were enabled again in the vite build (6469a0fe5b5f5abcc121305a5c471047226721b8), in certain cases the handler.js copy results in duplicate code. As example in the final build, dynamically imported modules might import their dependencies from the original entry-server.js instead of the handler.js copy, this would result in the following chain:
1. handler.js copied from entry-server.js (therefore has code of dep1, dep2, dep3)
2. handler.js dynamically imports SomeComponent.js
2. SomeComponent.js doesnt know about handler.js, imports dep2 from entry-server.js
3. entry-server.js has code for dep1, dep2, dep3
4. The final build includes dep1, dep2 and dep3 from handler.js and from entry-server.js
So by removing the handler.js copy and directly importing entry-server.js we …
> fix: remove entry-server handler copy in adapters

- packages/start-netlify/entry-edge.js
This fixes a bug in `entry-edge.js` that caused it to use the removed handler instead of importing `entry-server.js` directly. This bug was introduced in #770 and affected the edge function on Netlify.
> Fix error when use edge function in netlify adapter

- packages/start-vercel/index.js
[discord thread](https://discord.com/channels/722131463138705510/1083879274739675256)
trying to covert `process.cwd()` to a URL on windows would result in it thinking the drive is the protocol and get a invalid file path
`C:\` vs `file:///C:/`. vite exposes normalizePath which solves this issue
> fix: vercel adapter normalize windows paths

- examples/with-prisma/src/root.css
- examples/with-prisma/src/routes/[...404].tsx
- examples/with-prisma/src/routes/index.tsx
The prism example uses tailwind classes even though it doesn't have tailwind,
so these classes don't take effect.
This PR replaces them with a bit of CSS additions to `main.css`
for example:
```html
<main class="w-full p-4 space-y-2">
<h1 class="font-bold text-3xl">Hello {user()?.username}</h1>
<h3 class="font-bold text-xl">Message board</h3>
<button onClick={() => refetchRouteData()}>Refresh</button>
<Form>
<button name="logout" type="submit">
Logout
</button>
</Form>
</main>
```
> Remove tailwind classes from prisma example

- packages/start/api/index.ts
- test/api-routes-test.ts
Fixes #806
This fixes an issue with routes like
`/:param/` being scored higher than
routes like `/static`
> fix: api route scoring algorithm

- docs/core-concepts/api-routes.md
The example route for trpc `routes/api/trpc/[...].ts` is not a valid route for vercel deployments.
if you use a route with a param on `...` vercel during deployment will error with. 
Error: Builder returned invalid routes: ["Route at index 6 has invalid `src` regular expression \"^/api/trpc/(?<...>[^/]+)$\"."]
generated `.vercel/output/config.json`
```json
{
"version": 3,
"routes": [
{
"src": "/assets/(.*)",
"headers": {
"Cache-Control": "public, max-age=31556952, immutable"
},
"continue": true
},
{
"handle": "filesystem"
},
{
"src": "/api/trpc/(?<...>[^/]+)",
"dest": "/api"
},
{
"src": "/.*",
"dest": "/render"
}
]
}
```
[discord issue](https://discord.com/channels/722131463138705510/910635844119982080/1090429884175749120)
change the route param to match what the community does in …
> docs: api-routes change trpc route param name

- packages/start/api/internalFetch.ts
- packages/start/api/types.ts
With Cloudflare at least, `internalFetch` is mostly useless in many situations, as environment variables are only available through the event, and are reset to `{}` by `internalFetch`.
Also, `locals` is the most common place for middleware to store request context, and as middleware isn't run again when `internalFetch` is used, it's useful to be able to pass this through from the parent request.
> allow internalFetch to pass env and locals

- packages/start/node/fetch.js
The value of `req.headers.origin` can be a string "null". We need to consider this situation.
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin
> Check string "null" for req.headers.origin

- packages/start-static/index.d.ts
- packages/start-static/package.json
Fixes this TS error.
```ts
// vite.config.ts
import { defineConfig } from "vite";
import solid from "solid-start/vite";
import adapter from "solid-start-static"; // 🔴 Could not find a declaration file for module 'solid-start-static'.
export default defineConfig({
plugins: [
solid({ adapter: adapter() }),
],
});
```
> [start-static] Add index.d.ts

- examples/bare/package.json
- examples/hackernews/package.json
- examples/todomvc/package.json
- examples/with-auth/package.json
- examples/with-authjs/package.json
- examples/with-mdx/package.json
- examples/with-prisma/package.json
- examples/with-solid-styled/package.json
- examples/with-tailwindcss/package.json
- examples/with-vitest/package.json
- examples/with-websocket/package.json
- packages/start/package.json
- pnpm-lock.yaml
- test/template/package.json
Vite 4.3 is a quite significant update in terms of [performance](https://vitejs.dev/blog/announcing-vite4-3.html).
It's included in the [latest astro](https://github.com/withastro/astro/releases/tag/astro%402.3.1) (2.3.1)
> Bump astro to 2.3.1 to update vite to 4.3

- packages/start/package.json
This will make navigating from npm to this repo and docs easier.
> Add repository and website information to solid-start's package.json

- packages/start/astro/index.js
- pnpm-lock.yaml
- pnpm-workspace.yaml
- test/package.json
- test/playwright.config.ts
Previously we were always using the default port value in the Astro plugin. Now we either pass through [`process.env.PORT`](https://github.com/withastro/astro/blob/50bf66e4df8ac9b427e653a48cb8e4e84913d8f2/packages/integrations/node/src/standalone.ts#L39) (which is what Astro uses) or pick a random port - preferring numbers close to the default values.
The parallelization baked into the test infrastructure revealed this issue.
Now, 78/89 tests are passing ✨. There's 3 different kinds of failures left:
<details><summary>Network Idle Check</summary>
</details> 
<details><summary>TypeError: terminated</summary>
</details> 
<details><summary>Checking for `[data-testid=redirected]`</summary>
</details>
> fix: Allow multiple instances of solid-start on the same computer. Should fix e2e tests.

- packages/start/astro/index.js
The `config.server.port` from astro.config.ts  is currently ignored, which feels like a bug.
> Use port provided in astro config if present

- examples/with-authjs/package.json
Fixes #899 by updating the @auth/core dependency to 0.5.1 to resolve dependency tree.
> Updates dependency in AuthJS example to fix build error

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/question.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/issues.yml
Plus up the `.github` features by adding templates to issue creation and PRs for a better user experience for the community.
> ci: add issue & PR templates

- packages/start/bin.cjs
SPA client build will hang/fail because of whitespace in path. #913 
Building works.
> fix SPA client build failing because of whitespace in path

- packages/start/data/createRouteAction.tsx
In case of error `createServerAction$` returns undefined as a result, but typings don't:
```tsx
import { FormError } from 'solid-start'
import { createServerAction$ } from 'solid-start/server'
export default function Page() {
const [action, submit] = createServerAction$(async (formData: FormData) => {
if (formData.get('hasError')) {
throw new FormError('Validation failed')
}
return 'demo'
})
return (
<submit.Form
onsubmit={async (event) => {
event.preventDefault()
const formData = new FormData(event.currentTarget)
const result = await submit(formData)
console.log(action.result === result) // true
console.log(action.result) // type: string | undefined
/* ACTUAL:   */ console.log(result) …
```
> RouteAction returns undefined in case of error

- packages/start/data/createRouteAction.tsx
When you use the `createRouteAction` controller using the `Form` it returns without an argument, the types are set to `never` which results in an TS/IDE error.
This is because the typing incorrectly forces the return value based on if someone passes `FormData` as an argument which may not always be the case.
- Updates the types to use the correct return for the component while utilizing the type as a Union/alternate so the IDE or TS doesn't error, allowing users to still use the `Form` magic component without needing arguments.
- Also fixes current actual type errors in the file from not using the `unknown as` pattern.
Example use case, when using Supabase Auth, the API's have to run …
> fix(data): update Form types in createRouteAction.tsx

- examples/bare/package.json
- examples/hackernews/package.json
- examples/todomvc/package.json
- examples/with-auth/package.json
- examples/with-authjs/package.json
- examples/with-mdx/package.json
- examples/with-prisma/package.json
- examples/with-solid-styled/package.json
- examples/with-tailwindcss/package.json
- examples/with-trpc/package.json
- examples/with-vitest/package.json
- examples/with-websocket/package.json
- package.json
- packages/start-aws/package.json
- packages/start-cloudflare-pages/package.json
- packages/start-cloudflare-workers/package.json
- packages/start-deno/package.json
- packages/start-netlify/package.json
- packages/start-node/package.json
- packages/start-static/package.json
- packages/start-vercel/package.json
- packages/start/bin.cjs
- packages/start/package.json
- pnpm-lock.yaml
- test/package.json
- test/template/package.json
Vite is moving fast, and a lot has happened since 4.1.4, both for performance and fixes.
Vite 4.1.4 is being used
Vite 4.4.6 is being used
> Bump Vite to 4.4.6 in 0.2.x main branch

- packages/start/node/fetch.js
In undici >=5.19.0
Set-Cookie appears multiple times in headers. Server iterates over all set-cookie keys and only the last one will be set. Splitting does nothing here as the cookies are already splitted.
In undici 5.18.0
Set-Cookie appears only once in headers. Server splits the string and setHeader works as expected when passing in an array.
https://github.com/solidjs/solid-start/blob/52d44e2cad33faf3dc40148520d7ae41086dd6a8/packages/start/node/fetch.js#L160-L164
Now works in both versions.
fixes #953
> fix setting multiple set-cookie headers on response in undici >= 5.19.0

- packages/start/index.tsx
- packages/start/types.ts
When running the latest version of solid-start with the latest version of typescript, there are node_module errors that are not ignored like:
```bash
node_modules/.pnpm/solid-start@0.2.27_@solidjs+meta@0.28.6_@solidjs+router@0.8.2_solid-js@1.7.8_solid-start-node@0.2.19_vite@4.1.4/node_modules/solid-start/islands/router.ts:152:5 - error TS2552: Cannot find name '_$DEBUG'. Did you mean 'debug'?
152     _$DEBUG("mounted islands router");
```
Updates the index file to export all the types from `./types` vs. importing the file. I find this works as a better solution regarding libraries and DX.
> fix(start): types are not being exported properly in build

- packages/start/bin.cjs
I am honestly intimidated by writing a test in a project that already has established testing conventions, so I did not do this.
It is outlined in #958
If the `.solid/inspect` folder doesn't exist, it is created.
Fixes #958
> Fix building with `inspect: false`

- packages/start/vite/plugin.js
When you try to use storybook with a solid-start project you'll run into this issue: https://github.com/solidjs/solid-start/issues/822
A simple if statement to check if `vite.httpServer` exists before using it. The documentation on the `vite.httpServer` field also comments that this field can be null when using it in a middleware so I doubt it's a problem with vite.
> check to see if httpService exists before using it

- packages/start-vercel/index.d.ts
This will not the force the user to pass an empty object when using the vercel adapter
> fix vercel: make input optional

- packages/start/bin.cjs
`require` the CJS version of Vite
`import` the ESM version of Vite. The next major version of Vite may start producing warnings when Vite is required to encourage people to move off of the legacy CJS syntax and onto modern ESM. We should make a change now to get ahead of it and ensure users don't see this warning
> import vite rather than requiring it

- packages/start/node/fetch.js
This replaces defaulting to http which is not always correct nor safe.
This feature was removed in an older commit (https://github.com/solidjs/solid-start/commit/f69826f#diff-cf234a385fd7788d61976c078d5d093b2de418c259f1f7b3a15adb46ee1cedc3).
This commit re-implements said feature but with the standard of checking the "x-forwarded-proto" header or defaulting to "https". A standard which is already used in start-vercel: https://github.com/solidjs/solid-start/blob/925ea73b7f38b2126b1440a69ab25160dd8c6c16/packages/start-vercel/entry.js#L58 https://github.com/solidjs/solid-start/blob/925ea73b7f38b2126b1440a69ab25160dd8c6c16/packages/start-vercel/entry-prerender.js#L57
The current behavior …
> Get correct protocol when creating request.

- packages/start-static/index.js
start command does not work on windows because spawn is called without shell.
works on windows.
fixes #986
> fix: start command of static adapter not working on windows

- packages/start/entry-client/StartClient.tsx
Not sure how to test this: Do we have any tests that set a flag in vite, and then run the app to see there are no errors?
We could also move the code change into `@solidjs/router`, but this is a fix for SolidStart, and I'm not sure where it makes the most sense to add this small guard.
Setting this in `vite.config.ts`:
```
base: 'http://localhost:1234'.
```
Would cause Solid's router to crash, because it wasn't expecting base urls to include origins. Solid's router expects a base path, without an origin.
Before we pass Vite's BASE_URL to Solid's router, check for and remove any origin, by checking if the BASE_URL starts with `'http'`.
Closes #979
> Stop choking if BASE_URL includes origin (fix #979)

- packages/start-vercel/index.js
0.3.x does not work on node 16.
Updated runtime config to node 18 on the vercel adapter.
fixes #983
> fix: vercel build not working because runtime config is set to node 16

- packages/start-vercel/index.js
Breaking on version 0.3.2 on vercel on settings headers.
Vercel are using nodejs 18.x as default version for functions and start-vercel was using 16.x and with the new version (0.3.2) of solid-start was breaking on setting headers.
https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js#node.js-version
I suggest generating a new version 0.4.x because it can break other projects and need some tests
> feat[start-vercel]: upgrade functions to run with nodejs18.x

- packages/start-cloudflare-pages/entry.js
There were actually two bugs:
- The complete url is used to check for file endings causing 404 if the url ends with a query param that looks like a file ending.
`http://localhost?test=bad.png` would causes 404. 
- If the request for the static asset returns anything other than 200 the cloudflare error page will be shown instead of letting solid-start handle the request.
- Only looking at the pathname for file ending.
- If the request for static asset does not return 200 or 304 solid-start handels the request.
fixes #963
> fix: how cloudflare pages adapter checks for static asset request and give start a chance to handle request if not found

- packages/start/router.tsx
See [#982](https://github.com/solidjs/solid-start/issues/982) the 2nd issue.
I made adjustments to the `useRouteData` overload in line with the `RouteDataFunc` return type inference first added by otonashi [here](https://github.com/solidjs/solid-router/pull/263)
This restores the ability to correctly infer nested routeData type. However, this seems only to work when using the type `RouteDataFuncArgs` instead of `RouteDataArgs`. I am not sure if there are breaking side-effects, it only fixes this specific issue. I have added an example to the [stackblitz mentioned in the issue](https://stackblitz.com/edit/solid-ssr-vite-nh2rkt?file=src%2Froutes%2Ffixed.tsx).
This might not be the …
> Fix: Infer useRouteData return type for nested routeData

- package.json
- packages/start/package.json
- pnpm-lock.yaml
- test/template/package.json
Build output of examples inside the solid-start repo don't work.
Only inside the solid-start repo. Projects initialized with create-solid cli are **not** affected.
```
pnpm i
pnpm --filter example-bare run build
pnpm --filter example-bare run start
```
Result:
Counter button not working. Browser console showing:
```console
Uncaught TypeError: Cannot read properties of null (reading 'push')
at nn (entry-client-0002a3d6.js:1:1062)
at Object.fn (entry-client-0002a3d6.js:1:5465)
at ln (entry-client-0002a3d6.js:1:2337)
at Pe (entry-client-0002a3d6.js:1:2280)
at oe (entry-client-0002a3d6.js:1:834)
at Object.fn (entry-client-0002a3d6.js:1:5323)
at ln (entry-client-0002a3d6.js:1:2337)
at Pe …
```
> fix: examples build output not working inside the solid-start repo and update lock file

- packages/start/fs-router/router.js
The router does not generate the same path for a renamed index as it would for an index file.
Example:
|Index|Id|Path|Index (Renamed)|Id|Path|
|------|--|------|----------|-|----|
|index.tsx|/index|/|(home).tsx|/(home)||
|test/index.tsx|/test/index|`/test/`|test/(test).tsx|/test/(test)|`/test`|
This happens because `toPath` in `path-utils.js` removes every segment looking like a route group from the id which includes renamed index.
This also causes the static adapter to not generate an index.html for routes with a renamed index as it relies on the trailing slash.
When processing a route file, after creating the route config, check if the route id ends with a renamed index and add a …
> fix: router not generating same path for renamed index as for index file

- packages/start/entry-client/StartClient.tsx
Closes #96
When embedding a SolidStart app into a larger javascript app, users may need to customize the router source/integration, to avoid messing with the parent/host apps url. Users could use an in-memory based router, a [search-param based router](https://github.com/solidjs/solid-router/pull/291), hash-based router, etc.
There aren't any existing tests for `<StartClient`. I think in the future it would be good to add a "solid-as-a-micro-frontend" example, and we could add a test which ensures that example app renders with [`searchParamIntegration`](https://github.com/solidjs/solid-router/pull/291)
Use `patch-package` to pass in routerProps
Users can customize router source/integration.
> Allow passing in `routerProps` to `<StartClient`

- packages/start/islands/vite-plugin.js
One path is not being normalized breaking island hydration when build on windows.
Islands working when build on windows.
> fix: islands not hydrating when build on windows

- packages/start/server/render.ts
When requesting a page the `api` and `inlineServerFunctions` middleware gets called twice.
This happens because this two middlewares are called again inside the render middleware.
https://github.com/solidjs/solid-start/blob/043577a6400b8461baa2345e70b665f86da9692f/packages/start/entry-server/index.ts#L40
https://github.com/solidjs/solid-start/blob/043577a6400b8461baa2345e70b665f86da9692f/packages/start/server/render.ts#L15-L17
Created by the big merge. 
`server/render.ts` = original (before merge)
`entry-server/index.tsx` = new (after merge)
On page request the two middlewares get only called once.
Decided to keep the new code.
> fix: api and inlineServerFunctions middleware being called twice on page request

- packages/start/node/globals.js
```
3 | 
4 | // FIXME: Bun does not support this assignment.
5 | // We only assign if the runtime is not Bun.
6 | //
7 | // https://bun.sh/guides/util/detect-bun
8 | Object.assign(globalThis, Streams);
^
TypeError: Attempted to assign to readonly property.
at /private/tmp/solid/test/node_modules/solid-start/node/globals.js:8:0
at processTicksAndRejections (:1:2602)
```
Ready for #1059
> feat(start/node): Don't `Object.assign` on Bun

- packages/start-bun/README.md
- packages/start-bun/entry.js
- packages/start-bun/index.js
- packages/start-bun/package.json
- packages/start/node/globals.js
- packages/start/vite/plugin.js
- pnpm-lock.yaml
Experimental but works 🚀
The `--bun` flag is essential; otherwise, this server will be spawned by Node.
```bash
export START_ADAPTER="solid-start-bun"
bun run --bun build
bun run --bun start
```
wrk command: `wrk -t8 -c500 -d10s --latency "http://localhost:3000"`
system: macOS 13.5.2, on Apple M1.
| Platform | Base RAM usage | Requests/sec | RAM usage after `wrk` |
| --- | --- | --- | --- |
| Node | 22.2MB | 3107.68 | 126.5MB |
| Bun | 16.8MB | 7057.49 | 112.2MB |
> feat(bun): Add bun adapter

- packages/start/dev/server.js
- packages/start/vite/plugin.js
Providing a network IP as Host option is ok for Vite but errors because of Solid's logging - it only accounts for `local` addresses.
See [Discord](https://discord.com/channels/722131463138705510/910635844119982080/1150662412337426482)
If no `local` address defined, try `network` address.
Should have no runtime implication since these values are only collected for logging.
> fix: using network host errors during logging

- packages/start/entry-client/mount.tsx
- packages/start/fs-router/router.js
- Avoid overwriting existing debug namespaces
- Use "start:" prefix for debug messages in router
- Log both route-matches and route-data matches
see #1083
Existing value of `localStorage.debug` is maintained, `'start:*'` is added to it, if needed.
> Avoid overwriting localStorage.debug

- packages/start-netlify/entry-edge.js
- packages/start-netlify/index.js
When deploying as a Netlify edge function, it explicitly does not handle any paths containing a "." character.
These paths fall through to the default Netlify 404 page (not the project's own 404).
All requests are handled by the edge function. If the project has its own 404 page, we don't ever see the default Netlify 404.
I've manually tested that this covers the following cases:
- static asset (with or without `.` in name)
- dynamic routes (with or without `.` in name)
- internal `fetch` of static asset (from `public`)
- internal `fetch` of dynamic route
If you'd like me to put together a test, let me know. It's not really specific to Netlify so I guess it doesn't belong in this …
> Allow . in Netlify edge function paths

- packages/start-new/config/server-components.js
Fails to load `server-runtime.jsx` because the path is outputed with unescaped backslashes.
```console
21:42:37 [vite] Pre-transform error: Failed to load url C:UsersDavideDesktopsolid-startpackagesstart-newconfigserver-runtime.jsx (resolved id: C:UsersDavideDesktopsolid-startpackagesstart-newconfigserver-runtime.jsx) in C:/Users/Davide/Desktop/solid-start/examples/hackernews/src/lib/api.ts. Does the file exist?
21:42:37 [vite] Error when evaluating SSR module /src/lib/api.ts: failed to import "C:UsersDavideDesktopsolid-startpackagesstart-newconfigserver-runtime.jsx"
|- Error: Failed to load url C:UsersDavideDesktopsolid-startpackagesstart-newconfigserver-runtime.jsx (resolved id: C:UsersDavideDesktopsolid-startpackagesstart-newconfigserver-runtime.jsx) in …
```
> [vinxi] fix use server directive on windows

- packages/start/root/Scripts.tsx
Before https://github.com/solidjs/solid-start/commit/f351f42ba8566cbfa72b483dd63d4debcb386230 when NODE_ENV was set to something other than `development` or `production` you would get `ProdScripts`.
After that commit you get no hydration script in that case because `isProd` and `isDev` would both be false.
*Note: isDev is determined by checking import.meta.env.MODE and not import.meta.env.DEV* 
Return `ProdScripts` unless `isDev` is true. This restores the previous behavior and still prevents ending up with two hydration scripts in dev.
Reference: [Discord](https://discord.com/channels/722131463138705510/910635844119982080/1170127171965173832)
> fix missing hydration script when NODE_ENV is not dev or prod

- packages/start/config/server-runtime.jsx
It seems that ReadableStream writes are windowed, and so immediate Promises are getting batched alongside the sync output. I'm not sure if it's the server or the client that's doing the batching, but since we have a newline separator for the output we can safely extract the target value (the first line).
Example of a failing case:
```js
async function example() {
'use server';
// Our target here is the object, however since the output is batched,
// the initial streamed output consists of two lines: the object and
// the resolver call, the latter being the one captured as the target.
return {
immediate: Promise.resolve('foo');
};
}
```
> fix: server fn deserialization

- packages/start/config/index.d.ts
Start server typed as any
{ start: { server: any}}
Start server config typed as NitroConfig
> fix: add nitro config type

- README.md
- docs/components/tooltip.tsx
- docs/routes/api/vite.md
- vite.config.ts
- wrangler.toml
Reopened from #1140 and #1147 
This PR updates seroval to 1.0, where Web API have been moved out of the core serialization in the form of the plugins. This release is also important for deserialization (which Start relies on in client-to-server communication) so that kinda fixes potential issues in the future, the biggest being string deserialization.
> feat: seroval 1.0

- docs/routes/getting-started/project-setup.mdx
… it for you
The documentation has a command to create a my-app folder before running `create solid`, but the tool will ask you for your folder name already. If you follow the current docs you will end up with solid start installed in my-app/my-app
Docs don't include this step, and rely on the create solid command to guide you through the process.
> [DOCS] Remove app folder creation command because it's included

- packages/start/config/server-handler.js
- packages/start/package.json
- packages/start/server/StartServer.tsx
- packages/start/server/spa/StartServer.tsx
- pnpm-lock.yaml
A mistake we made is that `$R` only generates if we are actually serializing any data on the server. The mistake here is that we won't know if a server function, which is dependent on the same variable, would be called on the client-side.
This fix ensures that server function responses are guaranteed to have `$R` to be initialized.
Fixes #1186 
edit:
This PR also fixes an issue with server function streaming responses (not necessarily for Promises but for AsyncIterators)
> Fix global `$R`

- examples/basic/src/routes/about.tsx
this simply add a minimal `About` page to the basic example, so users don't click on the only active link and hit "Page not found". It's of course interesting to show how to do 404, but since this example is going to be many peoples very first exposure to solid-start it's probably best not to give the impression that routing is breaking.
> Add about page to basic example

- packages/start/config/index.js
no other way of cloning plugins without their scope right now
Fixes https://github.com/solidjs/solid-start/issues/1195
Right now the user sends a list of plugins in the `plugins` option. If these plugins depend on keeping some scope that they use to decide what to, there will be issues as we use the same plugins list for multiple router. I want to encourage people to use the fn version of the plugins config, but its a deviation from the default vite API, but only by the slightest and actually provides powerful pattern.
This adds support for the `plugins: () => [....]` format, while keeping the array format intact.
This was important for example for the `imagetools` plugin because it …
> allow sending plugins fn (to get different instances for each router)

- package.json
- pnpm-lock.yaml
- scripts/bump.js
vinxi packages not covered.
Should behave as before.
- Added cli builder [citty](https://github.com/unjs/citty)
- Added option `--vinxi` to also bump vinxi packages
- Refactor bump process
```sh
pnpm bump 0.4.2 --vinxi
```
If vinxi should always be updated like it's done for solid-js let me know. In that case I would remove citty. No point in adding an extra package.
> update bump script and add option to update vinxi packages

- packages/start/config/index.js
- packages/start/shared/dev-overlay/styles.css
- It seems that `error-stack-parser` and `source-map-js` are not being transformed by Vite and so this PR fixes it so that they are included in `optimizeDeps` by default.
- This PR also fixes some style issues.
- Fixes #1219
> Fix dev overlay

- packages/start/config/index.d.ts
vite-plugin-solid options are not optional
vite-plugin-solid options are optional
I assume that it was probably marked not optional by mistake.
> fix: make vite-plugin-solid options optional

- packages/start/config/index.js
- packages/start/config/server-fns-runtime.jsx
- packages/start/config/server-runtime.jsx
There's no way of defining a base path for routeData. Navigation to a route with routeData fails as /_server returns 404.
https://discord.com/channels/722131463138705510/910635844119982080/1194290696341950464
Base path added to /_server requests.
> fix: Add baseURL to server-fns and server-runtime

- packages/start/shared/routes.ts
When having a baseURL, API routes 404.
API routes work with base path.
________
baseURL is removed before matching API routes. 
```
export default defineConfig({
start: {
server: {
baseURL: "/asd",
},
},
});
```
> fix(matchAPIRoute): Strip baseURL from path

- packages/start/config/server-runtime.jsx
- This PR adds the `ChunkReader` utility class.
- The purpose of this class is for proper consumption of chunks that are being streamed by the server functions request. Previously, we only deserialize the first valid seroval chunk with the assumption that the first response chunk is a valid seroval chunk. However the browser interprets it differently, that is, if the chunk size is too large, the browser will split the "valid chunk" into smaller chunks, leading into a deserialization error.
- `ChunkReader` ensures that the first chunk is a valid chunk. If it's invalid, it will attempt to read a new chunk, and check if part of the chunk is a valid seroval chunk. This process repeats until the stream is drained.
- Fixes #1243 
Test app:
```js
// @refresh reload
import { createEffect, …
```
> fix: Add `ChunkReader`

- .changeset/neat-apricots-try.md
- packages/start/config/server-handler.js
Currently when running solid-start in a edge runtime (cloudflare, netlify, vercel) the posting of data to the _server endpoint and `formData` to an action causes an error `A hanging Promise was canceled` (run in wrangler) that is coming from nitro -> https://github.com/unjs/nitro/issues/1721
Not causing this error any more
> fix edge runtime errors reading formData and jsonData from request body

- packages/start/server/middleware.ts
1. second parameter is not a usual Response object. Only body is
guaranteed to be present on it.
2. export types for middlewares, so that apps can use them
Current before-response middlewares are told to treat second parameter as a usual Response object, which does not reflect reality
New behaviour copies types from H3, thus guaranteeing that the only "public" property of response is a body
> Use proper types for response middlewares

- .changeset/wild-yaks-flash.md
- examples/with-unocss/package.json
- examples/with-vitest/package.json
- package.json
- pnpm-lock.yaml
I couldn't build the unocss example - it was because it wasn't bumped to vinxi 0.2.x like the rest of the example. Also set vite consistently to 4.5.x (like vinxi), where currently both 4.4.6 and 4.4.9 are used.
> fix unocss example

- .changeset/many-eggs-move.md
- packages/start/shared/ErrorBoundary.tsx
Fixes #1311
```sh
yarn dlx create-solid
//... (I picked Tailwind + TypeScript)
yarn dev --open
```
In the console, the following error appears:
```
Uncaught SyntaxError: The requested module '/_build/node_modules/.vite/deps/solid-js.js?v=0fd153d1' does not provide an export named 'ParentProps' (at ErrorBoundary.tsx:2:49)
```
The error prevents client-side interaction other than navigation.
Building the application and running production mode does _not_ have the error.
No more syntax error in browser.
I verified this works by manually modifying the code from NPM when creating my application.
> [!NOTE]
> This was not reproducible within the solid-start repository. I suspect it has to do …
> fix: ensure ParentProps is declared as a type import

- packages/start/config/server-handler.ts
> Fix serialization for server functions

- .changeset/funny-spies-think.md
- packages/start/config/server-handler.ts
- packages/start/tsconfig.json
- pnpm-lock.yaml
Server functions throw error if they are called without arguments, please see: https://github.com/solidjs/solid-start/issues/1328
They no longer throw error if called without arguments
> Fix: calling server functions without arguments

- .changeset/hip-insects-ring.md
- packages/start/package.json
module auto import fix (loosing the extra `./`)
Currently the proposed import is showing e.g. `@solidjs/start/./server`
as in screenshot is showing the proper import `@solidjs/start/server`
> fix auto import proposal

- .changeset/clever-ties-act.md
- examples/bare/package.json
- examples/basic/package.json
- examples/experiments/package.json
- examples/hackernews/package.json
- examples/notes/package.json
- examples/todomvc/package.json
- examples/with-auth/package.json
- examples/with-mdx/package.json
- examples/with-prisma/package.json
- examples/with-solid-styled/package.json
- examples/with-tailwindcss/package.json
- examples/with-trpc/package.json
- examples/with-unocss/package.json
- examples/with-vitest/package.json
- package.json
- packages/start/package.json
- packages/start/server/fetchEvent.ts
- pnpm-lock.yaml
Related to
- https://github.com/nksaraf/vinxi/issues/136
- https://github.com/solidjs/vite-plugin-solid/pull/127
- https://github.com/solidjs/solid-start/issues/1123
I've found usage of `vite/runtime` (link below), so I don't trust vinxi 0.3.x, at least the `vinxi run` to be compatible with vite 4:
https://github.com/nksaraf/vinxi/commit/576440cd342de0e926fead2ced45b2410097b9e3#diff-1f1d67ddefb4f54313fdeafa8e44b64ad7b264539430e97790d1cd4414756581L401
**I went through all the examples to check it didn't break anything. This manual method flagged [an issue](https://github.com/nksaraf/vinxi/issues/192) with vinxi 0.3.0, which is resolved by 0.3.1.**
Vinxi 0.2.1  (vite 4 default)
Vinxi …
> Vinxi 0.2.1 -> 0.3.3 (Note: this changes default from vite 4 -> 5)

- examples/bare/package.json
- examples/basic/package.json
- examples/experiments/package.json
- examples/hackernews/package.json
- examples/notes/package.json
- examples/todomvc/package.json
- examples/with-auth/package.json
- examples/with-mdx/package.json
- examples/with-prisma/package.json
- examples/with-solid-styled/package.json
- examples/with-tailwindcss/package.json
- examples/with-trpc/package.json
- examples/with-unocss/package.json
- examples/with-vitest/package.json
- package.json
- packages/start/package.json
- pnpm-lock.yaml
The issues forcing a locking of vinxi to 0.3.4 have been resolved by now. The version [wasn't properly locked](https://github.com/solidjs/solid-start/blob/bc003f628b97ff2dbb114f8d381447bf14319d35/packages/start/package.json#L49) (maybe intentionally) inside packages/start, so it gave some [conflicts](https://github.com/nksaraf/vinxi/issues/227) on local solid-start development. 
Seems like a changeset isn't needed because `@solidjs/start` isn't pinned.
> Bump vinxi to ^0.3.9 (unpin version)

- .changeset/quiet-meals-heal.md
- packages/start/package.json
License is added so https://www.jsdocs.io/package/@solidjs/start can be used.
> Update package.json to include license

- .changeset/kind-mirrors-trade.md
- packages/start/shared/dev-overlay/CodeView.tsx
If a library used plain MJS for their code, or just plain CJS it ended up being
that the code view in the development overlay would not recognize the file type because
Shiki expects `mjs` and `cjs` to be passed into it as JavaScript.
Before actually passing in the language to the highlighter it checks if the file extension is
`mjs` or `cjs` and then assumes the language is `js` instead.
> fix(dev-overlay): Code view breaking if the file extension was mjs or cjs

- README.md
- docs/routes/getting-started/project-setup.mdx
```
$ bunx create-solid@latest
error: Script not found "create-solid@latest"
```
The corrected bunx command for "create-solid@latest" has been updated in the project's README and documentation, resolving the "Script not found" error.
N/A
> fix: script invocation error for "create-solid@latest"

- examples/notes/src/components/NoteEditor.tsx
- examples/notes/src/routes/new.tsx
I found it a bit annoying that the title was "Untitled", not as a placeholder but as the actual value. Now there is a "Title" placeholder instead, and it's a required field.
Before:
After (if you click save without typing)
> Set title required and add placeholder

- .changeset/pink-seals-wonder.md
- packages/start/config/index.d.ts
defineConfig returns any
defineConfig returns router
This should allow to extend router, [example](https://github.com/nksaraf/vinxi/issues/5#issuecomment-1974903835):
```js
const app = defineConfig({
server: {
experimental: {
websocket: true,
},
},
});
// Currently:
// Unsafe call of an `any` typed
// value.eslint[@typescript-eslint/no-unsafe-call](https://typescript-eslint.io/rules/no-unsafe-call)
app.addRouter({
name: "websocket",
type: "http",
handler: "./src/websocket.ts",
target: "server",
base: "/_ws",
});
export default app;
```
> defineConfig return type

- README.md
- docs/routes/getting-started/project-setup.mdx
The current project bootstrap command for solid with bun doesn't work as it errors out with.
```
$ bunx create solid
error: could not determine executable to run for package create 
```
Which is obvious as `bunx` technically is the same as npx/pnpx (execute an npm package executable (CLI), and automatically installing into a global shared cache if not found in `node_modules`). Currently it's looking for the package `create` rather than the `create command` which is causing that error.
Additional Info: I think it might be a issue with bun installation as when installed using a package manager such as (pnpm install -g bun), it doesn't create the correct symlinks of ``bun x`` to ``bunx`` …
> fix: bun project create command with solid

- .changeset/cool-eagles-eat.md
- packages/start/src/server/index.tsx
Unfortunately `export * from "./types.ts"` doesn't not work when importing from moduleResolution `NodeNext` and `export type * from "./types.ts"` doesn't work either. But I really need the type in solid primitives where I cannot change to moduleResolution `node` therefore we need to export all types separately.
I have not really found any information on the internet why this doesn't work. ChatGPT meant that there is a proposal for a former typescript that should already be implement, but I neither found the proposal nor did it work with the latest dev version so I guess that was just a missinformation.
> Export types properly

- docs/routes/api/FileRoutes.md
- docs/routes/core-concepts/data-loading.mdx
- docs/routes/core-concepts/routing.md
* A couple of docs pages have mentions of`<Routes>` component that was removed since Solid Router v0.9.
* The root component file name in one place is written as `root.tsx`, instead of default `app.tsx` in `FileRoutes.md`.
* There is a likely mistake in component name in the section explaining how `load` function works in `data-loading.mdx`
* All mentions of `<Routes>` are replaced with `<Router>`
* The `root.tsx` file name is replaced with `app.tsx` in `FileRoutes.md`.
* Changed the component name from `Routes` to `Page` in `data-loading.mdx`
> docs: update mentions of routes to router, etc.

- packages/start/src/runtime/server-handler.ts
- packages/start/src/runtime/server-runtime.ts
node.js returns incorrect string length on occuring of special charaters. Use encoded data length instead.
fixing #1408 
data.length in `createChunk` is less than the `(new TextEncoder().encode(data)).length`
not use data.length for buffer process
> fix(SerovalChunk): incorrect buffer length on special chars

- CONTRIBUTING.md
Seems all the dependencies need to be built out first otherwise you end up with an error about not being able to resolve: `@solidjs/start/server`. It seems there is no `node_modules/@solidjs/start/dist` directory.
Following the `CONTRIBUTION.md` does not work in the current state from a fresh start.
Build out all of the dependencies first.
> Update contribution notes to help with running the first time

- .changeset/fifty-nails-repair.md
- packages/start/src/server/StartServer.tsx
- packages/start/src/server/renderAsset.tsx
Assets rendered to the head of the document do not include the `nonce` if set, eg:
```js
export default createHandler((context) => (
<StartServer document={{ assets, children, scripts }}>
<html>
<head>
{assets}
</head>
<body>
{children}
{scripts}
</body>
</html>
</StartServer>
), (context) => ({ nonce: 'some-random-nonce' }));
```
Results in:
```html
<html>
<head>
<link rel="stylesheet" href="…" />
<script type="module" src="/_build/@vite/client" id="vite-client" />
</head>
<body>
<script type="module" nonce="some-random-nonce" src="...entry-cleint.tsx" />
</body>
</html>
```
```html
<html>
<head>
<link rel="stylesheet" nonce="some-random-nonce" href="…" />
<script type="module" …
```
> fix: ensure nonce is passed to all assets

- .github/workflows/deploy-docs.yml
- .github/workflows/doc-checks.yml
- .github/workflows/test.yml
- .github/workflows/typecheck.yml
- CONTRIBUTING.md
- pnpm-lock.yaml
All the latest versions of CI actions require Node 20, which seems to be quite reasonable now that node 22 has been released.
> Update ci actions / pnpm 9 / node 20

- .changeset/wise-avocados-lay.md
- packages/start/src/server/pageEvent.ts
During development `app.css` is only loaded in the browser via javascript, resulting in a flash of unstyled content.
`app.tsx` is registered for asset collection in the pageEvent on the server. This way `app.css` and other potential css assets of `app.tsx` are added to the document head, during server side rendering.
I am not 100% happy with the inlined `src/app.tsx`, do we have a proper way to access the path to `app.tsx`?
How it currently looks in a browser with disabled js:
How it should look:
owser with disabled js:
@nksaraf helped me to find the proper place to debug the issue 🙏.
> fix: add app.tsx assets to page event in dev env

- .changeset/good-coins-suffer.md
- packages/start/src/runtime/server-handler.ts
- packages/start/src/server/handler.ts
solid-start detects, that "Location" header is specified and tells vinxi to execute redirect, but it always uses default 302 code.
After this patch, solid-start checks if app-developer specified custom HTTP-status code and if it is one of valid redirect codes.
> ✨ Respect custom status-codes on redirects

- .changeset/wicked-wolves-fix.md
- examples/bare/tsconfig.json
- examples/basic/tsconfig.json
- examples/experiments/tsconfig.json
- examples/hackernews/tsconfig.json
- examples/notes/tsconfig.json
- examples/todomvc/tsconfig.json
- examples/with-auth/tsconfig.json
- examples/with-authjs/tsconfig.json
- examples/with-mdx/tsconfig.json
- examples/with-prisma/tsconfig.json
- examples/with-solid-styled/tsconfig.json
- examples/with-tailwindcss/tsconfig.json
- examples/with-trpc/tsconfig.json
- examples/with-unocss/tsconfig.json
- examples/with-vitest/tsconfig.json
-> The examples still build successfully
The examples have `moduleResolution` set to `node`, which is outdated and only compatible with cjs. This can lead to resolution issues with esm only libraries.
Reference: https://www.typescriptlang.org/tsconfig/#moduleResolution
By using `moduleResolution: "bundler"`, we're making sure to also support esm modules. the vite starter uses this too (`pnpm create vite`)
> fix: use `moduleResolution: "bundler"` in examples

- .changeset/twenty-monkeys-marry.md
- packages/start/config/fs-router.js
- packages/start/config/index.js
When building with `ssr: false`, the ssr + server-fn builds still transform + bundle all of the route components in filesystem routes.
This doesn't really make sense, since the ssr build will only ever be used during prerendering, which just renders `entry-server.tsx` and `app.tsx`, and `server-fn` only invokes `App` with `dataOnly` set on the router so none of the route components are actually used.
This PR adds a `dataOnly` config to `SolidStartServerFileRouter` which makes it omit the default exported component from all routes. Non-default exported components work the same and `export const route` is still included since it's needed on the server for SFM.
> Omit route components from non-SSR builds when `ssr: false`

- examples/with-vitest/package.json
- pnpm-lock.yaml
When I run `pnpm test` and `pnpm coverage` in the `with-vitest` example, I get the following errors
- `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite-plugin-solid'`
- `MISSING DEPENDENCY  Cannot find dependency '@vitest/coverage-v8'`
Without the missing required dependencies, the scripts will run as expected
> build(with-vitest): :heavy_plus_sign: add missing dependencies

- .changeset/mighty-teachers-guess.md
- packages/start/src/router/lazyRoute.ts
- packages/start/src/server/StartServer.tsx
If during SSR a vite error is encountered (such as a module not existing after a rename), vinxi's `import` function will throw, leading to the dev server crashing instead of being shown on the error overlay.
The error is now caught, the dev server no longer crashes, and the error is shown in the overlay.
When the module isn't found, `lazyRoute` will just return a no-op component so that the route can continue to resolve essentially as a no-op, since the error will surface itself in the Vite overlay anyway (not sure how to make it appear in the SS error overlay). 
This solves at least part of https://github.com/nksaraf/vinxi/issues/119
> Fix 'Failed to resolve import' crash during ssr

- examples/bare/src/app.tsx
- examples/basic/src/components/Counter.tsx
- examples/experiments/src/components/Counter.tsx
- examples/with-mdx/src/components/Counter.tsx
- examples/with-trpc/src/components/Counter.tsx
- examples/with-vitest/src/components/Counter.tsx
fixes #1517.
New projects created from specific templates use a `button` without specifying the `type` attribute, which defaults to `submit`, not `button`, and that can be unexpected.
Templates explicitly specify `button` type attributes as `button`.
> fix: ambiguous attribute for `button`

- package.json
- pnpm-lock.yaml
This updates the `rimraf` dependency.
`solid-start` uses `"rimraf": "^3.0.2",`.
```
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
```
`solid-start` uses `"rimraf": "^5.0.7",`.
> fix: usage of deprecated dependency `rimraf`

- .changeset/clever-jars-explode.md
- packages/start/config/index.d.ts
- [] Tests for the changes have been added (for bug fixes / features)
The types for `config.vite.server` currently allow all of Vite's `server` options, many of which are irrelevant since Vinxi overrides or disables them. This can lead to confusion (#1435) around where to configure things like dev server host and port.
I've changes the type of `config.vite.server` to omit some entries that don't do anything in Solid Start (and Vinxi for that matter):
- `middlewareMode`: Hardcoded to `true` by Vinxi. This stops Vite from spawning HTTP servers, making all the below options unnecessary:
- `port`: Should be provided with `--port` or `PORT`
- `strictPort`
- `host`: Should be provided with …
> Omit some keys from Vite server config

- .changeset/flat-mugs-travel.md
- packages/start/src/runtime/server-handler.ts
Responses thrown inside server functions don't get re-thrown on the client, as they aren't sent to the client with `X-Error` set.
`X-Error` will be set when Responses are thrown inside server functions
Having read through https://github.com/solidjs/solid-router/issues/387, maybe this header should only be set for thrown redirects? Though personally I'd expect returning/throwing to be isomorphic no matter what is returned/thrown
Closes #1512
> Set X-Error for thrown Responses

- .changeset/fifty-shrimps-cross.md
- packages/start/src/server/fetchEvent.ts
Makes behaviour of HttpStatusCode and fetchEvent a bit more consistent
Setting `event.response.statusCode` in non-AsyncLocalStorage environments currently throws an error from deep inside FetchEvent.
HTTPStatusCode will now throw when calling `getRequestEvent` rather than while setting `statusCode`, which is a bit more understandable imo.
> Pass event to getResponseStatus in set statusCode

- examples/with-auth/src/lib/index.ts
- examples/with-auth/src/lib/server.ts
- examples/with-drizzle/src/api/server.ts
- examples/with-prisma/src/lib/index.ts
- examples/with-prisma/src/lib/server.ts
Session updates in the examples were returning `user.id` from the updater function, which was being spread into the session data.
`userId` is the only property on sessions.
Closes #1536
> Don't return user.id from session updates

- packages/start/config/index.js
Outlined in [1559](https://github.com/solidjs/solid-start/issues/1559)
TL;DR production builds are not adding server action chunks when `experimental.islands` are enabled
Chunks are generated as expected
> Add `serverComponents.server()` to server-fns plugins when `experimental.islands` is enabled.

- .changeset/chilled-phones-sin.md
- packages/start/src/runtime/server-handler.ts
The changes from #1521 broke the form parsing in Node, it threw the error `[h3] [unhandled] TypeError: Response body object should not be disturbed or locked`.
This fixes the handling for Node, yet tries to keep the functional aspects from the edge runtime workarounds #1282 and #1521. **I couldn't test this fix on edge runtimes** - @supersoniko could you maybe check if your azure preset still works after this fix ☺️?
> fix: dont use node request as body in handleServerFunction

- .changeset/quiet-mirrors-judge.md
- packages/start/src/server/fetchEvent.ts
`getFetchEvent` is flaky, creating & storing multiple `fetchEvents` per `h3Event`. The reason for this is vinxi duplicating the code including the `fetchEventSymbol` per router (https://github.com/nksaraf/vinxi/issues/51), e.g. if you console.log the symbol https://github.com/solidjs/solid-start/blob/23b01da59b2e6a0e0139686605a7cbf8d723be97/packages/start/src/server/fetchEvent.ts#L16 you will notice that the console.log is executed twice during startup. Also if you log `Object.getOwnPropertySymbols(h3Event)` in `getFetchEvent` you get `[ Symbol(fetchEvent), Symbol(fetchEvent) ]` on requests that affect multiple vinxi routers.
`getFetchEvent` will maximally create one `fetchEvent` per …
> fix: store fetchEvent in h3 context

- .changeset/thin-swans-yell.md
- packages/start/src/router/routes.ts
API routes with paths containing international characters are never matched and do not work.
API routes containing international characters match and work as expected, consistent with other file routes.
For example an API route "/api/거" will never be matched currently. I don't think even naming the file/directory "%EA%B1%B0" (which would be an ugly workaround regardless) works here, so there is no way to accomplish this with the current broken behavior.
Normal file routes like "/거" match and work correctly, so this change makes API routes behave consistently with other routes.
> encode api url components

- examples/bare/src/app.css
- examples/basic/src/components/Counter.css
- examples/experiments/src/components/Counter.css
- examples/with-mdx/src/components/Counter.css
- examples/with-solid-styled/src/components/Counter.tsx
- examples/with-trpc/src/components/Counter.css
- examples/with-vitest/src/components/Counter.css
Small change but I think it makes the example a bit nicer showing that you can click the button.
Cursor doesn't show a pointer when hovering over the counter button.
Cursor does show a pointer when hovering over the counter button.
> Add cursor:pointer in Counter component examples

- .changeset/long-pumpkins-behave.md
- packages/start/src/shared/dev-overlay/DevOverlayDialog.tsx
- packages/start/src/shared/dev-overlay/index.tsx
Certain `ErrorEvent`s triggered on `window` do not have an `.error` property. One of such is the `ResizeObserver loop completed with undelivered notifications.` error, caused by `ResizeObserver` ([Details](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors)). These errors are not handled properly by the dev overlay, as can be seen in the attachments. They also are console logged as `null`.
`ErrorEvent` with no `.error` property are passed directly to the dev overlay and handled there as good as possible (sadly they do not include a stacktrace). Also instead of console logging `null`, such `ErrorEvents` are logged directly.
Before fix:
After fix:
> fix: pass errorless ErrorEvent to dev overlay

- examples/with-vitest/package.json
- pnpm-lock.yaml
This bumps all the deps in the with-vitest example.
It doesn't require any changes to the code apart from package.json. I check the vitest ui still run as well.
> Update with-vitest example to vitest  2

- .changeset/perfect-clocks-repair.md
- packages/start/config/fs-router.js
- packages/start/src/router/routes.ts
- packages/start/src/server/handler.ts
Fixes #1657
HEAD requests to API endpoints fail, unable to define them manually
1. Allows `export const HEAD: APIHandler = async () => { … };` as API endpoints
2. Falls back on GET api methods if no HEAD function is defined.
> fix(start): enable HEAD requests to API HEAD/GET routes

- docs/components/code-snippet.tsx
The new Deno 2 does work surprisingly well with node/vite projects, including Start - it can i.e. run the Notes example with single flight without modifications. This adds the create command to the start landing page.
Before
After
> Add deno create command to landing page

- .changeset/hot-students-tan.md
- package.json
- packages/start/package.json
- pnpm-lock.yaml
Continuation of
- https://github.com/nksaraf/vinxi/pull/417
This updates the vinxi and vite version in the root and /packages/start.
Despite packages/start 1.0.10 using the `@vinxi` 0.4.3 packages below, it does appear to be compatible with vinxi 0.5.0, but this pr aligns it all on the same vinxi 0.5.0 version:
```
"@vinxi/plugin-directives": "^0.4.3",
"@vinxi/server-components": "^0.4.3",
"@vinxi/server-functions": "^0.4.3".
```
Examples can be updated only after the release is cut, because they don't use "workspace:*" (due to create-solid).
I tested this by building locally and updated the with-vitest example, which works for `ssr:true/false`, and `vinxi dev/build/start`
> Upgrade to vinxi 0.5 (vite 6)

- examples/basic/src/routes/about.tsx
... in about.tsx
When using the *basic* starter template the *about.tsx* file contains a `Home` component, although it should be `About`
The *basic* starter template the *about.tsx* file contains a `About` component
> fix: rename 'Home' route component to 'About'

- package.json
There are many node_modules folders, and the current clean:root only takes out one.
The folders are located in:
16 examples
2 packages
1 root
Potentially more will come, such as a ./docs/node_modules, or additional examples
This cleans all of them, root and nested, and makes that the default behavior.
> Add clean:all command

- .github/workflows/typecheck.yml
PRs to docs are unable to merge because typecheck CI is not skipping and not running when the paths are ignored.
> Skip typecheck when changing ignored files

- .changeset/violet-snakes-dress.md
- packages/start/src/runtime/server-handler.ts
See https://github.com/solidjs/solid-start/issues/1673.
As described in https://github.com/solidjs/solid-start/issues/1673, submitting a Solid Action with the latest `netlify` nitro preset results in a 500 response from the `POST /server` with this error:
```
[nitro] [request error] [unhandled] Response body object should not be disturbed or locked
```
You can see this in the repro repo I shared in the issue or by clicking the button at https://672c1abc039334ad67383d7e--repro-solidstart-response-disturbed.netlify.app/.
Solid Actions work with the latest `netlify` nitro preset (i.e. a dummy handler results in a 200).
You can see this by linking this change into the repro repo I shared …
> fix: handle request body streaming with latest netlify preset

- pnpm-lock.yaml
- tests/server-function/cypress/e2e/server-function.cy.ts
- tests/server-function/package.json
- tests/server-function/src/app.tsx
- tests/server-function/src/routes/index.tsx
- tests/server-function/src/routes/is-server.tsx
- tests/server-function/src/routes/node-builtin.tsx
- tests/server-function/src/routes/npm-module.tsx
This makes sure the server function e2e tests also cover the ability to externalize modules.
As mentioned here: 
- https://github.com/solidjs/solid-start/pull/1715#issuecomment-2612592366
I've also split the suite into 4 tests:
- it("should have isServer false in the client")
- it("should have isServer true in the server function")
- it("should externalize node builtin in server function")
- it("should externalize npm module in server function")
> Add externalization test to server function suite 

- package.json
- pnpm-lock.yaml
- util/use-workspace-package-in-examples.js
This split the clean command to examples, packages, root - to more granularly clean up `.vinxi/`, `.output/`, `node_modules/`, `dist/` 
Also, since the clean:root command removes the `./node_modules/` where rimraf is currently installed, I found it was better to use `pnpx rimraf` to always allow running the clean commands
> Granular clean commands, build commands, util for using workspace package in examples

- pnpm-lock.yaml
This fixes the landing-page build error.... shown when running `pnpm run build` and `pnpm run start` and the runtime selector UI doesn't work.
The change to the lockfile fixes that. It's made by deleting the examples folder, running `pnpm i`, adding back the example folder, running `pnpm i` again.
> fix landing page error, caused by broken lockfile

- .github/workflows/compliance.yml
This sets up an automatic workflow to check if a PR is according to the contributing guidelines
- PR title is formatted according to conventional commits: in preparation for a release workflow that will generate releases in GH
- PR body refers to an issue: to make sure proper discussion and considerations were had before writing the code
- PR does not originate from protected branches (in our case, only `main`)
This workflow comes from Create-TypeScript-App by @joshuakgoldberg. Following this standard we can then also use the `post-release` workflow and the `release` workflow which will automate changes and feedback to PR authors about which release carries their code.
closes #1730
---
you can see in the comments below how the comment would work :)
> chore: Contributing Compliance Workflow

- .github/workflows/compliance.yml
This makes Compliance check not break the ci flow on missing issue link
https://github.com/mtfoley/pr-compliance-action/tree/main/?tab=readme-ov-file
> fix: don't fail on PR body

- package.json
> chore: use nvmrc instead of node engine

- .changeset/metal-ladybugs-check.md
- .gitignore
- packages/start/src/index.tsx
- packages/start/src/server/index.tsx
- packages/start/src/shared/serverFunction.tsx
- tests/server-function/cypress/e2e/server-function.cy.ts
- tests/server-function/src/functions/use-server-function-meta.ts
- tests/server-function/src/routes/server-function-meta-nested.tsx
- tests/server-function/src/routes/server-function-meta.tsx
`getServerFunctionMeta` is exported in `@solidjs/start/server`. Importing it can lead to circular import issues, because `StartServer` also resides in that entry. During such a circular import issue, `getServerFunctionMeta` will be undefined, resulting in an `getServerFunctionMeta is not a function` error.
- The old `getServerFunctionMeta` export in `@solidjs/start/server` is deprecated.
- A new `getServerFunctionMeta` export is added to `@solidjs/start`, which fixes the circular import.
PR for changing the `getServerFunctionMeta` docs entry: solidjs/solid-docs#1064
A similar change had to be made in the past related to `FileRoutes` (#1365).
This PR includes a new test for `getServerFunctionMeta`. If you run this test with the …
> fix: move getServerFunctionMeta export to @solidjs/start

- examples/pnpm-lock.yaml
- examples/with-solid-styled/app.config.ts
- examples/with-solid-styled/package.json
- examples/with-solid-styled/src/app.tsx
- Updates the solid-styled template to 0.12.0 (fixes SSR issue after dom-expressions fixed the useAssets sanitation, which solid-styled relies on)
> fix: solid-styled

- packages/start/src/runtime/server-handler.ts
fixes #1779
Currently server functions calls are expected to always provide the correct id and name. However in our use case we have had bots that try to access older id and name combinations which results in a 500 error.
This change treats not found server functions with a 404 response so that it provides better logging results in case an older or wrong id is being accessed directly.
> fix: return 404 when server function not found

- examples/pnpm-lock.yaml
- examples/with-tailwindcss/package.json
- examples/with-tailwindcss/postcss.config.cjs
- examples/with-tailwindcss/postcss.config.mjs
- examples/with-tailwindcss/src/app.css
This PR adopts tailwind 4, with the tried and tested postcss config that we know work.
This is a safe way of doing things, in comparison to using the new tailwind vite plugin:
- #1748 
- #1747
> chore: update tailwind example to v4

- .changeset/cold-scissors-clap.md
- packages/start/package.json
- packages/tests/cypress/e2e/server-function.cy.ts
- packages/tests/src/app.tsx
- packages/tests/src/functions/use-is-server-const.ts
- packages/tests/src/routes/is-server-const.tsx
- pnpm-lock.yaml
> fix: server function error when using export const

- .github/workflows/close-issue.yml
- .github/workflows/compliance.yml
- .github/workflows/issue-labelled.yml
I'm adding a few automations to the repository that will help us reduce the number of opened issues...copied from Vite.
- new label: **need reproduction**
- new action: triggers a bot comment asking and instructing how to make a reproduction
- cronjob: if the issue that needs reproduction is inactive for 3 days, it's closed.
I also added:
- **needs triage** so we know we need to look at it
- **good first issue** for low-hanging fruits
- **contributions welcome** we triaged but have no time to tackle it
> infra: automate issue management

- .changeset/lovely-comics-hammer.md
- packages/start/package.json
- packages/tests/cypress/e2e/server-function.cy.ts
- packages/tests/src/app.tsx
- packages/tests/src/functions/use-is-server-with-anon-default-export.ts
- packages/tests/src/routes/is-server-with-anon-default-export.tsx
- pnpm-lock.yaml
> fix: anonymous default exports with server functions

- examples/pnpm-lock.yaml
- examples/with-vitest/package.json
it's not showcased by the example, but vitest browser mode is enabled by this for solid-start too
> update with-vitest from vite 5 to 6

- examples/pnpm-lock.yaml
- examples/with-tanstack-router/package.json
- examples/with-tanstack-router/src/routeTree.gen.ts
There has been some fixes in the `@tanstack/solid-router` , e.g. that it now adds the route manifest.
> chore(with-tanstack-router example) bump deps

- .changeset/shy-rivers-punch.md
- examples/with-tanstack-router/app.config.ts
- examples/with-tanstack-router/src/app.tsx
- examples/with-tanstack-router/src/entry-client.tsx
- examples/with-tanstack-router/src/entry-server.tsx
- examples/with-tanstack-router/src/router.tsx
- packages/start/src/client/StartClient.tsx
- packages/start/src/client/index.tsx
- packages/start/src/client/spa/index.tsx
- packages/start/src/server/handler.ts
- packages/start/src/server/spa/handler.ts
- pnpm-lock.yaml
Enables SSR for tanstack router app
> feat: add ssr for tanstack router

- examples/pnpm-lock.yaml
- examples/with-authjs/package.json
update to latest mediakit/auth, that support latest solid-start
https://github.com/solidjs-community/mediakit/issues/148#event-16931585761
> chore(authjs example): bump to latest `@solid-mediakit/auth`

- packages/start/package.json
- packages/tests/cypress/e2e/server-function.cy.ts
- packages/tests/src/app.tsx
- packages/tests/src/functions/use-generator-server-function.ts
- packages/tests/src/routes/generator-server-function.tsx
- pnpm-lock.yaml
Fixes #1886 1886
Generators in server functions were not working
This upgrades tanstack server functions plugin which has the updated fix
> fix: generators with server functions

- .changeset/tasty-hounds-poke.md
- packages/start/src/runtime/server-runtime.ts
This fixes an infinite loop when a server function receives unexpected response like 403
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message></Error>
```
see issue #1898
There aren't any unit tests setup I could find to add a test for this.
This just fixes the infinite loop, but probably better error handling for response codes like 403 and response content types like should be made, it would be beneficial to get the response code and body to be able to gracefully handle errors on server functions - this requires some API design decisions?
> fix: infinite loop on unexpected response from server function (#1898)

- packages/landing-page/src/components/code-snippet.tsx
This PR updates the "create" command for Deno. [`init --npm`](https://docs.deno.com/runtime/reference/cli/init/) is the official command for this purpose. The documentation site was also recently updated to use `init --npm`.
> Update Deno quick start command

- pnpm-lock.yaml
now you'll get better type hints
> fix: vite config types

- CONTRIBUTING.md
- README.md
- **CONTRIBUTING.md**: Created a new CONTRIBUTING.md file, fully updated to reflect the latest repository structure and guidelines.
- **README.md**: Relocated monorepo details to CONTRIBUTING.md; centered badges and incorporated new logos; streamlined installation commands with the `-s` flag; added a link to SSG pre-rendering documentation.
> docs: Updated contribution guidelines and README

- .changeset/open-ducks-flash.md
- packages/start/src/server/fetchEvent.ts
`event.response.headers.has("does-not-exist")` returns `true`
`event.response.headers.has("does-not-exist")` returns `false`
> fix: `fetchEvent` -> `HeaderProxy` checks for `null` instead of `undefined`

- packages/landing-page/src/components/sections/rock-solid-dx.tsx
- fix is trivial; no issue is needed
- Website copy should not be tested
N/A
N/A
Fixes this mistake on https://start.solidjs.com/:
> Fix spelling of “whistles” on landing page
